### ISSUE TITLE
warning when train TSN2D on UCF101

### ISSUE THREAD

**Issue by shuxp** [open-mmlab/mmaction#101]
I am using pytorch1.2. It seems will fail if I change to 1.3.

When debug, it seems this warning comes out from SimpleConsensus, but I have no idea where to change it.

```
/pytorch/torch/csrc/autograd/python_function.cpp:638: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)
```

Looking for some help, thanks.

**Comment by shuxp** [comment]
It seems changed in v1.2, [details here](https://github.com/pytorch/pytorch/releases/tag/v1.2.0), and search 'Function without static forward method'. Now I am figuring out how to solve this.

**Comment by shuxp** [comment]
[simple_consensus.py](https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/segmental_consensuses/simple_consensus.py) file should be modified. In _SimpleConsensus class, should change self to ctx and change other relative things. It is a little difficult for me now...

**Comment by staceycy** [comment]
Degrade Pytorch1.2 to Pytorch1.0 solved the issue for me.

**Comment by loveunk** [comment]
I have [a commit ](https://github.com/loveunk/mmaction/commit/a33c3c8dadc61a421c909d1386033e2708d31a78)for this issue. It has been tested with PyTorch 1.4 and works.

**Comment by kennymckormick** [comment]
We rewrote the SimpleConsensus as nn.Module, it should be OK now.
