### ISSUE TITLE
TypeError: 'DataContainer' object does not support indexing

### ISSUE THREAD

**Issue by stevehjc** [open-mmlab/mmaction#106]
File "*****/mmaction/models/detectors/base.py", line 78, in forward
    num_modalities = int(num_modalities[0])
TypeError: 'DataContainer' object does not support indexing

```
cudatoolkit               9.2                           0    defaults
cudnn                     7.6.0                 cuda9.2_0    defaults
pytorch                   1.2.0           cuda92py36hd3e106c_0    defaults
mmcv                      0.2.13                   pypi_0    pypi
```

**Comment by wangbingo** [comment]
I had the same problem.
When  downgrade pytorch to 1.1.0, everything  goes  Ok.

**Comment by stevehjc** [comment]
> I had the same problem.
> When downgrade pytorch to 1.1.0, everything goes Ok.

I tried it, but the problem still exists.
```
pytorch                   1.1.0           cuda92py36h65efead_0    defaults
```

**Comment by stevehjc** [comment]
@wangbingo 
> I had the same problem.
> When downgrade pytorch to 1.1.0, everything goes Ok.

I tried it, but the problem still exists.
Could you tell me how you install pytorch 1.1.0? I use `conda install pytorch=1.1 cudatoolkit=9`
```
pytorch                   1.1.0           cuda92py36h65efead_0    defaults
```

**Comment by shuxp** [comment]
I run code with pytorch1.2, which is OK wich DataContainer.

**Comment by stevehjc** [comment]
I install by
`conda install pytorch=1.0 torchvision cudatoolkit=9.2 -c pytorch`
 it's OK.
