### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by janequist** [open-mmlab/mmaction#107]
Hi,

I've followed the given instructions and am getting the following errors with OpenCV build:
 21%] Built target opencv_perf_stitching_pch_dephelp
[ 21%] Linking CXX static library ../../lib/libopencv_test_flann_pch_dephelp.a
[ 21%] Built target opencv_test_flann_pch_dephelp
[ 21%] Linking CXX static library ../../lib/libopencv_test_stitching_pch_dephelp.a
[ 21%] Built target opencv_test_stitching_pch_dephelp
[ 21%] Built target gen_opencv_python_source
CMakeFiles/Makefile2:1042: recipe for target 'modules/CMakeFiles/ade.dir/all' failed
make[1]: *** [modules/CMakeFiles/ade.dir/all] Error 2
CMakeFiles/Makefile2:464: recipe for target '3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all' failed
make[1]: *** [3rdparty/protobuf/CMakeFiles/libprotobuf.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

Also with denseflow, the following errors:
make[2]: *** No rule to make target '/home/ubuntu/lib/mmaction/third_party/opencv-4.1.0/build/lib/libopencv_gapi.so.4.1.0', needed by 'extract_warp_gpu'.  Stop.
make[2]: *** Waiting for unfinished jobs....
make[2]: *** No rule to make target '/home/ubuntu/lib/mmaction/third_party/opencv-4.1.0/build/lib/libopencv_gapi.so.4.1.0', needed by 'extract_cpu'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object CMakeFiles/extract_cpu.dir/tools/extract_flow.cpp.o
[ 57%] Building CXX object CMakeFiles/extract_warp_gpu.dir/tools/extract_warp_flow_gpu.cpp.o
make[2]: *** No rule to make target '/home/ubuntu/lib/mmaction/third_party/opencv-4.1.0/build/lib/libopencv_gapi.so.4.1.0', needed by 'extract_gpu'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 64%] Building CXX object CMakeFiles/extract_gpu.dir/tools/extract_flow_gpu.cpp.o
make[2]: *** No rule to make target '/home/ubuntu/lib/mmaction/third_party/opencv-4.1.0/build/lib/libopencv_gapi.so.4.1.0', needed by 'libpydenseflow.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[ 71%] Building CXX object CMakeFiles/pydenseflow.dir/src/py_denseflow.cpp.o
CMakeFiles/Makefile2:146: recipe for target 'CMakeFiles/extract_cpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_cpu.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/extract_warp_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_warp_gpu.dir/all] Error 2
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/extract_gpu.dir/all' failed
make[1]: *** [CMakeFiles/extract_gpu.dir/all] Error 2
CMakeFiles/Makefile2:183: recipe for target 'CMakeFiles/pydenseflow.dir/all' failed
make[1]: *** [CMakeFiles/pydenseflow.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
 
The platform is Ubuntu 16.04.6 with all the updates. It seems to build ok for part of these libs. Sorry to bother with a build issue, but some of you who work with it everyday may know offhand on how to fix...any pointers?

Thx,
Jane

**Comment by Fovever1** [comment]
@mynameismaxz   i meet same problem，cmake-3.12，does it has the relationship with c_make version? maxz

**Comment by mynameismaxz** [comment]
> @mynameismaxz i meet same problem，cmake-3.12，does it has the relationship with c_make version? maxz

Yes, I just tried to compile OpenCV-4.1.0 with CMake-3.12 but it's found an error. I think cause that from cmake-3.12 was changed the parameter with CUDA compile. So, When I use default CMake to install from the ```apt-get```. I can compile them without error.

**Comment by kennymckormick** [comment]
We recommend using our [new version of denseflow](https://github.com/open-mmlab/denseflow), which is more efficient and easy to install. You can use [setup](https://github.com/innerlee/setup) to easily install all requirements.
