### ISSUE TITLE
missing file

### ISSUE THREAD

**Issue by banzhuan37** [open-mmlab/mmaction#11]
There's no extract_rgb_frames.bash file in data_tools/ucf101, how can I only extract RGB frames from videos?

**Comment by TotallyFine** [comment]
Following command should work
```shell
#! /usr/bin/bash env

cd ../
python build_rawframes.py ../data/ucf101/videos/ ../data/ucf101/rawframes/ --level 2 --ext mp4
echo "Raw frames (RGB only) Generated"
cd ucf101/
```

**Comment by zhaoyue-zephyrus** [comment]
Hi @banzhuan37 ,

Thanks @TotallyFine for this reply. You can simply remove the `--ext mp4` option as well.

```shell
#! /usr/bin/bash env

cd ../
python build_rawframes.py ../data/ucf101/videos/ ../data/ucf101/rawframes/ --level 2
echo "Raw frames (RGB only) Generated"
cd ucf101/
```

I am now looking into the compilation issue.
