### ISSUE TITLE
How to Set the Frame Rate for Extracting Optical Flow?

### ISSUE THREAD

**Issue by hellocv** [open-mmlab/mmaction#110]
Hello, thank you for your hard work, which really brings great convenience.

Meanwhile, when we use the code from ` mmaction/data_tools/build_rawframes.py/build_rawframes.py`  to extract optical flow, how can we set the frame rate? For example, can we set the frame rate as 30 fps for a new dataset?

Thank you for your help.

**Comment by kennymckormick** [comment]
For denseflow, you can not set the frame rate when extracting flow. But you can first convert your video to 30fps using ffmpeg.
