### ISSUE TITLE
Boost_INCLUDE_DIR NOTFOUND

### ISSUE THREAD

**Issue by jxyzhx15** [open-mmlab/mmaction#111]
I have a problem that Cmake can not find Boost_INCLUDE_DIR after I run 'OpenCV_DIR=../../opencv-4.1.0/build/  cmake ..'.

> -- Found Boost 1.71.0 at /usr/local/lib/cmake/Boost-1.71.0
--   Requested configuration: QUIET REQUIRED COMPONENTS python
-- BoostConfig: find_package(boost_headers 1.71.0 EXACT CONFIG REQUIRED QUIET HINTS /usr/local/lib/cmake)
-- Found boost_headers 1.71.0 at /usr/local/lib/cmake/boost_headers-1.71.0
-- BoostConfig: find_package(boost_python 1.71.0 EXACT CONFIG REQUIRED QUIET HINTS /usr/local/lib/cmake)
-- Found boost_python 1.71.0 at /usr/local/lib/cmake/boost_python-1.71.0
-- Boost toolset is clang10 (Clang 10.0.1.10010046)
-- Scanning /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant*.cmake
--   Including /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant-mt-shared-py3.7.cmake
--   [x] libboost_python37-mt.dylib
--   Including /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant-mt-static-py3.7.cmake
--   [ ] libboost_python37-mt.a
--   Including /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant-shared-py3.7.cmake
--   [x] libboost_python37.dylib
CMake Warning at /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant-shared-py3.7.cmake:69 (message):
  Target Boost::python already has an imported location
  '/usr/local/lib/libboost_python37-mt.dylib', which will be overwritten with
  '/usr/local/lib/libboost_python37.dylib'
Call Stack (most recent call first):
  /usr/local/lib/cmake/boost_python-1.71.0/boost_python-config.cmake:43 (include)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:117 (find_package)
  /usr/local/lib/cmake/Boost-1.71.0/BoostConfig.cmake:182 (boost_find_component)
  /usr/local/Cellar/cmake/HEAD-ac0b59e/share/cmake/Modules/FindBoost.cmake:266 (find_package)
  CMakeLists.txt:23 (FIND_PACKAGE)

--   Including /usr/local/lib/cmake/boost_python-1.71.0/libboost_python-variant-static-py3.7.cmake
--   [ ] libboost_python37.a
-- Adding boost_python dependencies: headers
-- Boost  found.
-- Found Boost components:
   python
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow
   used as include directory in directory /Users/koukin/Desktop/project/haha/dense_flow

-- Configuring incomplete, errors occurred!
See also "/Users/koukin/Desktop/project/haha/dense_flow/build/CMakeFiles/CMakeOutput.log".

I am using Mac ox 10.14.6, can anyone help me solving the problem.

Thx

yzhx

**Comment by mynameismaxz** [comment]
Hi, @jxyzhx15 

You could install libboost library.

**Comment by kennymckormick** [comment]
Seems not active. Close now. Feel free to reopen it if problems are not resolved.
