### ISSUE TITLE
error:does not appear to contain CMakeLists.txt

### ISSUE THREAD

**Issue by ray-boom** [open-mmlab/mmaction#112]
When I input **cmake .. -DUSE_CUDA=0** in Install Decord    it happened:**CMake Error: The source directory "/media/lhs/新加卷/mmaction/third_party/decord" does not appear to contain CMakeLists.txt.**
Do you know how to deal with it? thx

**Comment by mynameismaxz** [comment]
Hi, @ray-boom 

Could you check path to run ```cmake .. -DUSE_CUDA=0```. I think it may be an incorrect path.

**Comment by kennymckormick** [comment]
Hi, to install decord now u can use 'pip install decord' directly.
