### ISSUE TITLE
How can I combine two stream ?

### ISSUE THREAD

**Issue by buianhvu** [open-mmlab/mmaction#113]
Hello everyone, could I know how to use to code to combine the results from 2 trained model (1 with RGB frames, 1 with flow frames) ? Is there any available inside the code ?
Thank you so much !

**Comment by lmiles247** [comment]
Hi @buianhvu,
I posted asking a similar question #109. I believe we need to run the test script and grab the resulting scores for each stream, and then combine them by taking the average and running a softmax. Still waiting to hear from the authors. Please let me know if you figure out a solution!!

**Comment by buianhvu** [comment]
hi @lmiles247 , it seems that the solution is to fuse the results of 2 modalities from 2 separate model for different input modality. (the ratio might be 1 for RGB and 1.5 for Flow as I remember)

**Comment by kennymckormick** [comment]
> Hi @buianhvu,
> I posted asking a similar question #109. I believe we need to run the test script and grab the resulting scores for each stream, and then combine them by taking the average and running a softmax. Still waiting to hear from the authors. Please let me know if you figure out a solution!!

@lmiles247 is totally right. To fuse two modalities, you need to first get each modality's prediction, then fuse them with proper coefficient. We usually apply softmax before modality fusion.
