### ISSUE TITLE
RGB or BGR?

### ISSUE THREAD

**Issue by cinjon** [open-mmlab/mmaction#115]
Does TSN expect RGB input or BGR input? I am asking because the tsn_rgb_bninception.py config has `to_rgb=False` in img_norm_cfg and because, as far as I can tell, the rest of the pipeline is in BGR. For example, build_rawframes uses `mmcv.imwrite`, which uses cv2.imwrite (and that saves in BGR). Then, the files are read back in rawframes_dataset with `mmcv.imwrite`, which uses cv2.imread.

**Comment by kennymckormick** [comment]
I think it depends on the pretrain model you used, the color order should be consistent with your pretrain model. When you train TSN from scratch, RGB or BGR doesn't matter. You can set `to_rgb` in img_norm_cfg to control that.

**Comment by zhaoyue-zephyrus** [comment]
Hi @cinjon ,

@kennymckormick  is totally right. In your example, the `to_rgb=False` in `tsn_rgb_bninception.py` is because the (pretrained) caffemodel followed an input of `BGR`. We keep that to ensure finetuning.
