### ISSUE TITLE
where can I find recognizers?

### ISSUE THREAD

**Issue by cambridgeinch** [open-mmlab/mmaction#120]
https://github.com/open-mmlab/mmaction/blob/bb31acb5a060e351ba4261d94558fdf7f6bdfb5d/tools/test_recognizer.py#L10

I only find a file folder named recognizers but where can I find the function named recognizers. 
I cannot import a file folder if I use Google Colab to implement the code.

**Comment by kennymckormick** [comment]
You can safely remove 'import recognizers', seems it is not used in this piece of code. We will create a PR for code revision.
