### ISSUE TITLE
OSError: tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth is not a checkpoint file

### ISSUE THREAD

**Issue by JameesWang** [open-mmlab/mmaction#121]
Thank you very much for your outstanding work！**When I run** 
**`python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth`**
**I got an error:** **OSError: tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth is not a checkpoint file**
**Details are as follows：**
`The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "tools/test_recognizer.py", line 122, in <module>
    main()
  File "tools/test_recognizer.py", line 73, in main
    load_checkpoint(model, args.checkpoint, strict=True)
  File "/home/test/anaconda3/envs/mmaction/lib/python3.7/site-packages/mmcv/runner/checkpoint.py", line 171, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth is not a checkpoint file
`
**Looking forward to your reply! Thank you~**

**Comment by kennymckormick** [comment]
Hi, JameesWang, 
     You can run command `ckpt = torch.load('tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth')` and paste the result here. That might be helpful. Besides that, make sure there is a file at your checkpoint path.

**Comment by easoncat** [comment]
Hi, JameesWang. I met the same problem when I run the test code, you can add relative path before tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth, like ./data_tools/ucf101/modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth
