### ISSUE TITLE
ava performance

### ISSUE THREAD

**Issue by leaderj1001** [open-mmlab/mmaction#124]
The ava dataset does not exceed 16.03 mAP. How can you achieve 21.3 mAP?

**Comment by zhaoyue-zephyrus** [comment]
Hi @leaderj1001 

Thanks for trying our codebase. Would you mind sharing the training and testing command that you used?

Best,
Yue

**Comment by leaderj1001** [comment]
Thank you for your comment.
First, I really appreciate your awesome code.
All coding or data environments are equally matched. When training, I used the command "python ./tools/dist_train_detector.sh ./configs/ava/ava_fast_rcnn_nl_r50_c4_1x_kinetics_pretrain_crop.py 8 --validate".
When testing, I used the command "python ./tools/test_detector.py ./configs/ava/ava_fast_rcnn_nl_r50_c4_1x_kinetics_pretrain_crop.py ./work_dirs/epoch_12.pth"

Thank you :)

**Comment by zhaoyue-zephyrus** [comment]
Would you mind testing on the pre-trained model in [MODEL_ZOO](https://github.com/open-mmlab/mmaction/blob/master/MODEL_ZOO.md) first?

**Comment by leaderj1001** [comment]
When I using a pre-trained model, I can achieve 21.25 mAP.

Thank you.

**Comment by zhaoyue-zephyrus** [comment]
Could you briefly describe how you prepared the data? I am not sure if the difference comes from the data. People (@justimyhxu) in our group can reproduce the result with no difficulties.

**Comment by leaderj1001** [comment]
Thanks for your comments :)

Finally I got 21.4 mAP. Thank you.
However, there is one question. Why are training time validation mAP and
test_detector.py different?

Best regards,

Myeongjun Kim

**Comment by simobupt** [comment]
> The ava dataset does not exceed 16.03 mAP. How can you achieve 21.3 mAP?

I want to ask you about where I can find these two files.
data/ava/ava_video_resolution_stats.csv  &data/ava/ava_dense_proposals_train.FAIR.recall_93.9.pkl
Thank you.
