### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by easoncat** [open-mmlab/mmaction#126]
Hello, thanks for your great work!  However, when I run the test code 
`python ./tools/test_recognizer.py ./configs/ucf101/tsn_rgb_bninception.py ./data_tools/ucf101/modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth --gpus 1` ,
then I got
![微信图片_20200115162003](https://user-images.githubusercontent.com/46479973/72424732-691dd500-37c1-11ea-90b3-5c9c659f093f.jpg)

Could you help me solve the problem?
Thank you very much!

**Comment by kennymckormick** [comment]
Since our testing script needs to forward 25x10 images for TSN at a time, it may consume too much cuda memory. Once you get the 25x10 input for dataloader, you can split it to several pieces, forward each at a time, it needs much less memory.

**Comment by easoncat** [comment]
Hi, kennymckormick! Thank you for your help, I solve the problem.
