### ISSUE TITLE
Reproduction of 2D TSN experiment on RGB images (UCF101)

### ISSUE THREAD

**Issue by bryanyzhu** [open-mmlab/mmaction#13]
Hi there, thank you for the wonderful codebase. I followed the `Getting Started` page to train a 2D TSN experiment on RGB images of UCF101 dataset. 
```
./tools/dist_train_recognizer.sh configs/ucf101/tsn_rgb_bninception.py 8 --validate
```
I think I followed all the steps in the readme, but the best accuracy I can get is 84.31 (which is about 2% away from the number you reported, 86.41).

I also downloaded the reference model `tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth` and test it, the accuracy is indeed 86.41. This means your pre-trained model is good, and my data should be good too. Then the problem may lie in the training side, maybe I miss some important details. 

Could you help me to reproduce the result? Let me know if you need more information. Thank you very much.

**Comment by zhaoyue-zephyrus** [comment]
Hi @bryanyzhu 

Sorry for the late reply. Are you observing the accuracy from the training log? If so, then that 84.31% is probably okay because in the "val" phase, accuracy is obtained by using `num_segments=3`. By using `tools/test_recognizer.py`, the accuracy is obtained by using `num_segments=25`.

**Comment by bryanyzhu** [comment]
@zhaoyue-zephyrus Thank you for the reply. I used the `tools/test_recognizer.py` to get 84.31%. 

The highest number from my training log is 83.8. Although it is a little bit weird to me that using 25 segments doesn't give me more performance boost. (83.8 -> 84.3 is really small). Maybe I will train it again? Thank you.

**Comment by zhaoyue-zephyrus** [comment]
@bryanyzhu 
Just a quick re-training before sleeping: 85.77% test accuracy. (didn't use `--validate` just for a quick outcome). The thing I figure out may be different is the initialization for the classification head. Check it out here: https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/cls_heads/cls_head.py#L17: this param has been added for training Kinetics. When writing the first draft, it was `0.001` by default. That's when the provided model was trained.

It seems that `0.01` for a fine-tuned task like UCF-101 is a bit unstable. Also, the loss decreases far slower at the beginning. 

Could you run with `init_std=0.001` and see if it works? Simply add one line in the [config](https://github.com/open-mmlab/mmaction/blob/master/configs/ucf101/tsn_rgb_bninception.py#L22) with `init_std=0.001`.

**Comment by bryanyzhu** [comment]
@zhaoyue-zephyrus Thanks a lot for your quick response. I will retrain it and let you know how it goes.

**Comment by bryanyzhu** [comment]
@zhaoyue-zephyrus Looks like it works. I got 86.11% test accuracy. Thank you for pointing out the issue.

**Comment by walton-wang929** [comment]
hi guys, when I use 2D TSN experiment on RGB images of UCF101 dataset, got a worse resut: 

{"mode": "train", "epoch": 1, "iter": 10, "lr": 0.001, "time": 6.59968, "data_time": 4.79052, "memory": 16456, "loss_cls": 73.63762, "loss": 73.63762}
{"mode": "val", "epoch": 1, "iter": 19, "lr": 0.001, "top1 acc": 0.00978, "top5 acc": 0.06238}
{"mode": "train", "epoch": 2, "iter": 10, "lr": 0.001, "time": 6.2559, "data_time": 4.14773, "memory": 16456, "loss_cls": 4.62783, "loss": 4.62783}
{"mode": "val", "epoch": 2, "iter": 19, "lr": 0.001, "top1 acc": 0.01824, "top5 acc": 0.06794} 
{"mode": "train", "epoch": 3, "iter": 10, "lr": 0.001, "time": 6.54335, "data_time": 4.15391, "memory": 16456, "loss_cls": 4.60896, "loss": 4.60896}
{"mode": "val", "epoch": 3, "iter": 19, "lr": 0.001, "top1 acc": 0.02168, "top5 acc": 0.07904}
{"mode": "train", "epoch": 4, "iter": 10, "lr": 0.001, "time": 6.09087, "data_time": 4.07497, "memory": 16456, "loss_cls": 4.59705, "loss": 4.59705}
{"mode": "val", "epoch": 4, "iter": 19, "lr": 0.001, "top1 acc": 0.01057, "top5 acc": 0.08512}
{"mode": "train", "epoch": 5, "iter": 10, "lr": 0.001, "time": 5.98298, "data_time": 3.94384, "memory": 16456, "loss_cls": 4.59814, "loss": 4.59814}
{"mode": "val", "epoch": 5, "iter": 19, "lr": 0.001, "top1 acc": 0.02326, "top5 acc": 0.07322}
{"mode": "train", "epoch": 6, "iter": 10, "lr": 0.001, "time": 5.87847, "data_time": 4.291, "memory": 16456, "loss_cls": 4.60147, "loss": 4.60147}
{"mode": "val", "epoch": 6, "iter": 19, "lr": 0.001, "top1 acc": 0.0185, "top5 acc": 0.07851}
{"mode": "train", "epoch": 7, "iter": 10, "lr": 0.001, "time": 6.39616, "data_time": 4.34292, "memory": 16456, "loss_cls": 4.58668, "loss": 4.58668}
{"mode": "val", "epoch": 7, "iter": 19, "lr": 0.001, "top1 acc": 0.02035, "top5 acc": 0.08512} 
{"mode": "train", "epoch": 8, "iter": 10, "lr": 0.001, "time": 6.13934, "data_time": 3.92796, "memory": 16456, "loss_cls": 4.57444, "loss": 4.57444}
{"mode": "val", "epoch": 8, "iter": 19, "lr": 0.001, "top1 acc": 0.02062, "top5 acc": 0.08591} 
{"mode": "train", "epoch": 9, "iter": 10, "lr": 0.001, "time": 6.59786, "data_time": 4.96792, "memory": 16456, "loss_cls": 4.5666, "loss": 4.5666}
{"mode": "val", "epoch": 9, "iter": 19, "lr": 0.001, "top1 acc": 0.02326, "top5 acc": 0.09728} 
{"mode": "train", "epoch": 10, "iter": 10, "lr": 0.001, "time": 6.22923, "data_time": 4.37879, "memory": 16456, "loss_cls": 4.53772, "loss": 4.53772}
{"mode": "val", "epoch": 10, "iter": 19, "lr": 0.001, "top1 acc": 0.02353, "top5 acc": 0.10151}
{"mode": "train", "epoch": 11, "iter": 10, "lr": 0.001, "time": 6.02696, "data_time": 4.53345, "memory": 16456, "loss_cls": 4.52914, "loss": 4.52914}
{"mode": "val", "epoch": 11, "iter": 19, "lr": 0.001, "top1 acc": 0.03093, "top5 acc": 0.11684}
{"mode": "train", "epoch": 12, "iter": 10, "lr": 0.001, "time": 6.03086, "data_time": 4.49686, "memory": 16456, "loss_cls": 4.50453, "loss": 4.50453}
{"mode": "val", "epoch": 12, "iter": 19, "lr": 0.001, "top1 acc": 0.03833, "top5 acc": 0.13904}
{"mode": "train", "epoch": 13, "iter": 10, "lr": 0.001, "time": 5.4286, "data_time": 3.99259, "memory": 16456, "loss_cls": 4.499, "loss": 4.499}
{"mode": "val", "epoch": 13, "iter": 19, "lr": 0.001, "top1 acc": 0.03939, "top5 acc": 0.17076}
{"mode": "train", "epoch": 14, "iter": 10, "lr": 0.001, "time": 5.9655, "data_time": 3.30429, "memory": 16456, "loss_cls": 4.45963, "loss": 4.45963}
{"mode": "val", "epoch": 14, "iter": 19, "lr": 0.001, "top1 acc": 0.04547, "top5 acc": 0.18425}
{"mode": "train", "epoch": 15, "iter": 10, "lr": 0.001, "time": 5.97812, "data_time": 4.11405, "memory": 16456, "loss_cls": 4.42892, "loss": 4.42892}
{"mode": "val", "epoch": 15, "iter": 19, "lr": 0.001, "top1 acc": 0.06741, "top5 acc": 0.21174}
{"mode": "train", "epoch": 16, "iter": 10, "lr": 0.001, "time": 5.49566, "data_time": 3.29916, "memory": 16456, "loss_cls": 4.36183, "loss": 4.36183}
{"mode": "val", "epoch": 16, "iter": 19, "lr": 0.001, "top1 acc": 0.05604, "top5 acc": 0.21174}
{"mode": "train", "epoch": 17, "iter": 10, "lr": 0.001, "time": 5.61962, "data_time": 4.10749, "memory": 16456, "loss_cls": 4.31805, "loss": 4.31805}
{"mode": "val", "epoch": 17, "iter": 19, "lr": 0.001, "top1 acc": 0.07824, "top5 acc": 0.24134}
{"mode": "train", "epoch": 18, "iter": 10, "lr": 0.001, "time": 5.74654, "data_time": 3.40408, "memory": 16456, "loss_cls": 4.27423, "loss": 4.27423}
{"mode": "val", "epoch": 18, "iter": 19, "lr": 0.001, "top1 acc": 0.08855, "top5 acc": 0.27518}
{"mode": "train", "epoch": 19, "iter": 10, "lr": 0.001, "time": 5.33932, "data_time": 2.98646, "memory": 16456, "loss_cls": 4.22464, "loss": 4.22464}
{"mode": "val", "epoch": 19, "iter": 19, "lr": 0.001, "top1 acc": 0.08882, "top5 acc": 0.26249}
{"mode": "train", "epoch": 20, "iter": 10, "lr": 0.001, "time": 5.46231, "data_time": 4.00622, "memory": 16456, "loss_cls": 4.20768, "loss": 4.20768}
{"mode": "val", "epoch": 20, "iter": 19, "lr": 0.001, "top1 acc": 0.0867, "top5 acc": 0.2646}
{"mode": "train", "epoch": 21, "iter": 10, "lr": 0.001, "time": 5.78806, "data_time": 3.72811, "memory": 16456, "loss_cls": 4.11142, "loss": 4.11142}
{"mode": "val", "epoch": 21, "iter": 19, "lr": 0.001, "top1 acc": 0.10362, "top5 acc": 0.28972}
{"mode": "train", "epoch": 22, "iter": 10, "lr": 0.001, "time": 5.28719, "data_time": 3.49775, "memory": 16456, "loss_cls": 4.11703, "loss": 4.11703}
{"mode": "val", "epoch": 22, "iter": 19, "lr": 0.001, "top1 acc": 0.11314, "top5 acc": 0.31298}
{"mode": "train", "epoch": 23, "iter": 10, "lr": 0.001, "time": 5.32476, "data_time": 3.59142, "memory": 16456, "loss_cls": 4.09953, "loss": 4.09953}
{"mode": "val", "epoch": 23, "iter": 19, "lr": 0.001, "top1 acc": 0.10045, "top5 acc": 0.31007}
{"mode": "train", "epoch": 24, "iter": 10, "lr": 0.001, "time": 4.90421, "data_time": 3.12628, "memory": 16456, "loss_cls": 4.0542, "loss": 4.0542}
{"mode": "val", "epoch": 24, "iter": 19, "lr": 0.001, "top1 acc": 0.1134, "top5 acc": 0.31615} 
{"mode": "train", "epoch": 25, "iter": 10, "lr": 0.001, "time": 5.05663, "data_time": 3.18759, "memory": 16456, "loss_cls": 4.03631, "loss": 4.03631}
{"mode": "val", "epoch": 25, "iter": 19, "lr": 0.001, "top1 acc": 0.11525, "top5 acc": 0.31562}
{"mode": "train", "epoch": 26, "iter": 10, "lr": 0.001, "time": 5.42983, "data_time": 4.0069, "memory": 16456, "loss_cls": 4.02107, "loss": 4.02107}
{"mode": "val", "epoch": 26, "iter": 19, "lr": 0.001, "top1 acc": 0.13032, "top5 acc": 0.34444}
{"mode": "train", "epoch": 27, "iter": 10, "lr": 0.001, "time": 5.03418, "data_time": 2.42634, "memory": 16456, "loss_cls": 3.89932, "loss": 3.89932}
{"mode": "val", "epoch": 27, "iter": 19, "lr": 0.001, "top1 acc": 0.12741, "top5 acc": 0.32672}
{"mode": "train", "epoch": 28, "iter": 10, "lr": 0.001, "time": 4.95922, "data_time": 2.78061, "memory": 16456, "loss_cls": 3.93132, "loss": 3.93132}
{"mode": "val", "epoch": 28, "iter": 19, "lr": 0.001, "top1 acc": 0.13508, "top5 acc": 0.34867}
{"mode": "train", "epoch": 29, "iter": 10, "lr": 0.001, "time": 5.24887, "data_time": 3.81378, "memory": 16456, "loss_cls": 3.86994, "loss": 3.86994}
{"mode": "val", "epoch": 29, "iter": 19, "lr": 0.001, "top1 acc": 0.12371, "top5 acc": 0.32884}
{"mode": "train", "epoch": 30, "iter": 10, "lr": 0.001, "time": 5.30318, "data_time": 3.69758, "memory": 16456, "loss_cls": 3.92261, "loss": 3.92261}
{"mode": "val", "epoch": 30, "iter": 19, "lr": 0.001, "top1 acc": 0.13666, "top5 acc": 0.34444}
{"mode": "train", "epoch": 31, "iter": 10, "lr": 0.0001, "time": 4.59069, "data_time": 2.66315, "memory": 16456, "loss_cls": 3.83807, "loss": 3.83807}
{"mode": "val", "epoch": 31, "iter": 19, "lr": 0.0001, "top1 acc": 0.14592, "top5 acc": 0.36453}
{"mode": "train", "epoch": 32, "iter": 10, "lr": 0.0001, "time": 4.47446, "data_time": 3.03578, "memory": 16456, "loss_cls": 3.80689, "loss": 3.80689}
{"mode": "val", "epoch": 32, "iter": 19, "lr": 0.0001, "top1 acc": 0.1483, "top5 acc": 0.37272}
{"mode": "train", "epoch": 33, "iter": 10, "lr": 0.0001, "time": 4.72415, "data_time": 2.99083, "memory": 16456, "loss_cls": 3.74731, "loss": 3.74731}
{"mode": "val", "epoch": 33, "iter": 19, "lr": 0.0001, "top1 acc": 0.14459, "top5 acc": 0.35897}
{"mode": "train", "epoch": 34, "iter": 10, "lr": 0.0001, "time": 4.83533, "data_time": 3.00956, "memory": 16456, "loss_cls": 3.80953, "loss": 3.80953}
{"mode": "val", "epoch": 34, "iter": 19, "lr": 0.0001, "top1 acc": 0.14433, "top5 acc": 0.36347}
{"mode": "train", "epoch": 35, "iter": 10, "lr": 0.0001, "time": 4.51768, "data_time": 2.94599, "memory": 16456, "loss_cls": 3.76962, "loss": 3.76962}
{"mode": "val", "epoch": 35, "iter": 19, "lr": 0.0001, "top1 acc": 0.14724, "top5 acc": 0.37008}
{"mode": "train", "epoch": 36, "iter": 10, "lr": 0.0001, "time": 4.86958, "data_time": 2.58592, "memory": 16456, "loss_cls": 3.78939, "loss": 3.78939}
{"mode": "val", "epoch": 36, "iter": 19, "lr": 0.0001, "top1 acc": 0.14856, "top5 acc": 0.37008}
{"mode": "train", "epoch": 37, "iter": 10, "lr": 0.0001, "time": 4.78394, "data_time": 3.22931, "memory": 16456, "loss_cls": 3.76687, "loss": 3.76687}
{"mode": "val", "epoch": 37, "iter": 19, "lr": 0.0001, "top1 acc": 0.14274, "top5 acc": 0.37113}
{"mode": "train", "epoch": 38, "iter": 10, "lr": 0.0001, "time": 4.61635, "data_time": 3.04465, "memory": 16456, "loss_cls": 3.78416, "loss": 3.78416}
{"mode": "val", "epoch": 38, "iter": 19, "lr": 0.0001, "top1 acc": 0.14512, "top5 acc": 0.37034}
{"mode": "train", "epoch": 39, "iter": 10, "lr": 0.0001, "time": 5.02736, "data_time": 3.47707, "memory": 16456, "loss_cls": 3.81726, "loss": 3.81726}
{"mode": "val", "epoch": 39, "iter": 19, "lr": 0.0001, "top1 acc": 0.14565, "top5 acc": 0.37721}
{"mode": "train", "epoch": 40, "iter": 10, "lr": 0.0001, "time": 4.94822, "data_time": 3.32182, "memory": 16456, "loss_cls": 3.779, "loss": 3.779}
{"mode": "val", "epoch": 40, "iter": 19, "lr": 0.0001, "top1 acc": 0.1483, "top5 acc": 0.37113}
{"mode": "train", "epoch": 41, "iter": 10, "lr": 0.0001, "time": 4.7053, "data_time": 2.68197, "memory": 16456, "loss_cls": 3.69984, "loss": 3.69984}
{"mode": "val", "epoch": 41, "iter": 19, "lr": 0.0001, "top1 acc": 0.14909, "top5 acc": 0.37193}
{"mode": "train", "epoch": 42, "iter": 10, "lr": 0.0001, "time": 4.8742, "data_time": 2.90632, "memory": 16456, "loss_cls": 3.73803, "loss": 3.73803}
{"mode": "val", "epoch": 42, "iter": 19, "lr": 0.0001, "top1 acc": 0.14565, "top5 acc": 0.37325}
{"mode": "train", "epoch": 43, "iter": 10, "lr": 0.0001, "time": 4.60737, "data_time": 2.66877, "memory": 16456, "loss_cls": 3.79369, "loss": 3.79369}
{"mode": "val", "epoch": 43, "iter": 19, "lr": 0.0001, "top1 acc": 0.14644, "top5 acc": 0.37298}
{"mode": "train", "epoch": 44, "iter": 10, "lr": 0.0001, "time": 4.36718, "data_time": 2.68785, "memory": 16456, "loss_cls": 3.74887, "loss": 3.74887}
{"mode": "val", "epoch": 44, "iter": 19, "lr": 0.0001, "top1 acc": 0.15279, "top5 acc": 0.38012}
{"mode": "train", "epoch": 45, "iter": 10, "lr": 0.0001, "time": 4.07946, "data_time": 2.14321, "memory": 16456, "loss_cls": 3.7874, "loss": 3.7874}
{"mode": "val", "epoch": 45, "iter": 19, "lr": 0.0001, "top1 acc": 0.14909, "top5 acc": 0.38329}
{"mode": "train", "epoch": 46, "iter": 10, "lr": 0.0001, "time": 4.11809, "data_time": 1.74111, "memory": 16456, "loss_cls": 3.70572, "loss": 3.70572}
{"mode": "val", "epoch": 46, "iter": 19, "lr": 0.0001, "top1 acc": 0.14671, "top5 acc": 0.37721}
{"mode": "train", "epoch": 47, "iter": 10, "lr": 0.0001, "time": 4.18984, "data_time": 2.39014, "memory": 16456, "loss_cls": 3.72424, "loss": 3.72424}
{"mode": "val", "epoch": 47, "iter": 19, "lr": 0.0001, "top1 acc": 0.15279, "top5 acc": 0.38435}
{"mode": "train", "epoch": 48, "iter": 10, "lr": 0.0001, "time": 4.51257, "data_time": 2.97726, "memory": 16456, "loss_cls": 3.75075, "loss": 3.75075}
{"mode": "val", "epoch": 48, "iter": 19, "lr": 0.0001, "top1 acc": 0.14988, "top5 acc": 0.38541}
{"mode": "train", "epoch": 49, "iter": 10, "lr": 0.0001, "time": 4.08212, "data_time": 1.7789, "memory": 16456, "loss_cls": 3.67325, "loss": 3.67325}
{"mode": "val", "epoch": 49, "iter": 19, "lr": 0.0001, "top1 acc": 0.14935, "top5 acc": 0.38805}
{"mode": "train", "epoch": 50, "iter": 10, "lr": 0.0001, "time": 3.89519, "data_time": 1.78426, "memory": 16456, "loss_cls": 3.72147, "loss": 3.72147}
{"mode": "val", "epoch": 50, "iter": 19, "lr": 0.0001, "top1 acc": 0.15305, "top5 acc": 0.38805}
{"mode": "train", "epoch": 51, "iter": 10, "lr": 0.0001, "time": 4.18781, "data_time": 2.06871, "memory": 16456, "loss_cls": 3.68675, "loss": 3.68675}
{"mode": "val", "epoch": 51, "iter": 19, "lr": 0.0001, "top1 acc": 0.14856, "top5 acc": 0.38567}
{"mode": "train", "epoch": 52, "iter": 10, "lr": 0.0001, "time": 4.27388, "data_time": 2.37932, "memory": 16456, "loss_cls": 3.70923, "loss": 3.70923}
{"mode": "val", "epoch": 52, "iter": 19, "lr": 0.0001, "top1 acc": 0.15596, "top5 acc": 0.39492}
{"mode": "train", "epoch": 53, "iter": 10, "lr": 0.0001, "time": 3.91264, "data_time": 2.36107, "memory": 16456, "loss_cls": 3.71382, "loss": 3.71382}
{"mode": "val", "epoch": 53, "iter": 19, "lr": 0.0001, "top1 acc": 0.15147, "top5 acc": 0.3936}
{"mode": "train", "epoch": 54, "iter": 10, "lr": 0.0001, "time": 3.91469, "data_time": 2.50443, "memory": 16456, "loss_cls": 3.65068, "loss": 3.65068}
{"mode": "val", "epoch": 54, "iter": 19, "lr": 0.0001, "top1 acc": 0.15332, "top5 acc": 0.3944}
{"mode": "train", "epoch": 55, "iter": 10, "lr": 0.0001, "time": 4.08883, "data_time": 2.2749, "memory": 16456, "loss_cls": 3.74864, "loss": 3.74864}
{"mode": "val", "epoch": 55, "iter": 19, "lr": 0.0001, "top1 acc": 0.15305, "top5 acc": 0.3862}
{"mode": "train", "epoch": 56, "iter": 10, "lr": 0.0001, "time": 3.81447, "data_time": 2.27535, "memory": 16456, "loss_cls": 3.66713, "loss": 3.66713}
{"mode": "val", "epoch": 56, "iter": 19, "lr": 0.0001, "top1 acc": 0.15702, "top5 acc": 0.39466}
{"mode": "train", "epoch": 57, "iter": 10, "lr": 0.0001, "time": 3.66625, "data_time": 2.23502, "memory": 16456, "loss_cls": 3.68263, "loss": 3.68263}
{"mode": "val", "epoch": 57, "iter": 19, "lr": 0.0001, "top1 acc": 0.15596, "top5 acc": 0.3936}
{"mode": "train", "epoch": 58, "iter": 10, "lr": 0.0001, "time": 3.87044, "data_time": 2.38638, "memory": 16456, "loss_cls": 3.72128, "loss": 3.72128}
{"mode": "val", "epoch": 58, "iter": 19, "lr": 0.0001, "top1 acc": 0.15966, "top5 acc": 0.39704}
{"mode": "train", "epoch": 59, "iter": 10, "lr": 0.0001, "time": 3.37626, "data_time": 1.7942, "memory": 16456, "loss_cls": 3.68891, "loss": 3.68891}
{"mode": "val", "epoch": 59, "iter": 19, "lr": 0.0001, "top1 acc": 0.16072, "top5 acc": 0.39783}
{"mode": "train", "epoch": 60, "iter": 10, "lr": 0.0001, "time": 3.9391, "data_time": 2.41371, "memory": 16456, "loss_cls": 3.65772, "loss": 3.65772}
{"mode": "val", "epoch": 60, "iter": 19, "lr": 0.0001, "top1 acc": 0.15385, "top5 acc": 0.38858}
{"mode": "train", "epoch": 61, "iter": 10, "lr": 1e-05, "time": 3.79834, "data_time": 2.16193, "memory": 16456, "loss_cls": 3.65373, "loss": 3.65373}
{"mode": "val", "epoch": 61, "iter": 19, "lr": 1e-05, "top1 acc": 0.15808, "top5 acc": 0.3973}
{"mode": "train", "epoch": 62, "iter": 10, "lr": 1e-05, "time": 3.57298, "data_time": 2.10906, "memory": 16456, "loss_cls": 3.68258, "loss": 3.68258}
{"mode": "val", "epoch": 62, "iter": 19, "lr": 1e-05, "top1 acc": 0.15913, "top5 acc": 0.39704}
{"mode": "train", "epoch": 63, "iter": 10, "lr": 1e-05, "time": 3.93737, "data_time": 1.89961, "memory": 16456, "loss_cls": 3.69076, "loss": 3.69076}
{"mode": "val", "epoch": 63, "iter": 19, "lr": 1e-05, "top1 acc": 0.15596, "top5 acc": 0.39413}
{"mode": "train", "epoch": 64, "iter": 10, "lr": 1e-05, "time": 3.56181, "data_time": 1.90609, "memory": 16456, "loss_cls": 3.69993, "loss": 3.69993}
{"mode": "val", "epoch": 64, "iter": 19, "lr": 1e-05, "top1 acc": 0.16204, "top5 acc": 0.39281}
{"mode": "train", "epoch": 65, "iter": 10, "lr": 1e-05, "time": 3.64249, "data_time": 2.00628, "memory": 16456, "loss_cls": 3.66661, "loss": 3.66661}
{"mode": "val", "epoch": 65, "iter": 19, "lr": 1e-05, "top1 acc": 0.15623, "top5 acc": 0.39598}
{"mode": "train", "epoch": 66, "iter": 10, "lr": 1e-05, "time": 3.64164, "data_time": 1.88844, "memory": 16456, "loss_cls": 3.67771, "loss": 3.67771}
{"mode": "val", "epoch": 66, "iter": 19, "lr": 1e-05, "top1 acc": 0.16019, "top5 acc": 0.39413}
{"mode": "train", "epoch": 67, "iter": 10, "lr": 1e-05, "time": 3.31633, "data_time": 1.90259, "memory": 16456, "loss_cls": 3.67754, "loss": 3.67754}
{"mode": "val", "epoch": 67, "iter": 19, "lr": 1e-05, "top1 acc": 0.15781, "top5 acc": 0.39678}
{"mode": "train", "epoch": 68, "iter": 10, "lr": 1e-05, "time": 3.68104, "data_time": 2.24832, "memory": 16456, "loss_cls": 3.62924, "loss": 3.62924}
{"mode": "val", "epoch": 68, "iter": 19, "lr": 1e-05, "top1 acc": 0.15332, "top5 acc": 0.39704}
{"mode": "train", "epoch": 69, "iter": 10, "lr": 1e-05, "time": 3.32242, "data_time": 1.67757, "memory": 16456, "loss_cls": 3.6172, "loss": 3.6172}
{"mode": "val", "epoch": 69, "iter": 19, "lr": 1e-05, "top1 acc": 0.15993, "top5 acc": 0.3973}
{"mode": "train", "epoch": 70, "iter": 10, "lr": 1e-05, "time": 3.60735, "data_time": 1.75943, "memory": 16456, "loss_cls": 3.67713, "loss": 3.67713}
{"mode": "val", "epoch": 70, "iter": 19, "lr": 1e-05, "top1 acc": 0.15887, "top5 acc": 0.39572}
{"mode": "train", "epoch": 71, "iter": 10, "lr": 1e-05, "time": 3.17165, "data_time": 1.69223, "memory": 16456, "loss_cls": 3.69616, "loss": 3.69616}
{"mode": "val", "epoch": 71, "iter": 19, "lr": 1e-05, "top1 acc": 0.15358, "top5 acc": 0.39149}
{"mode": "train", "epoch": 72, "iter": 10, "lr": 1e-05, "time": 7.13597, "data_time": 5.64428, "memory": 16456, "loss_cls": 3.67512, "loss": 3.67512}
{"mode": "val", "epoch": 72, "iter": 19, "lr": 1e-05, "top1 acc": 0.16442, "top5 acc": 0.40021}
{"mode": "train", "epoch": 73, "iter": 10, "lr": 1e-05, "time": 8.98034, "data_time": 6.27443, "memory": 16456, "loss_cls": 3.67745, "loss": 3.67745}
{"mode": "val", "epoch": 73, "iter": 19, "lr": 1e-05, "top1 acc": 0.16098, "top5 acc": 0.39942}
{"mode": "train", "epoch": 74, "iter": 10, "lr": 1e-05, "time": 3.82793, "data_time": 1.96539, "memory": 16456, "loss_cls": 3.62814, "loss": 3.62814}
{"mode": "val", "epoch": 74, "iter": 19, "lr": 1e-05, "top1 acc": 0.15834, "top5 acc": 0.3973}
{"mode": "train", "epoch": 75, "iter": 10, "lr": 1e-05, "time": 3.17487, "data_time": 1.61266, "memory": 16456, "loss_cls": 3.67736, "loss": 3.67736}
{"mode": "val", "epoch": 75, "iter": 19, "lr": 1e-05, "top1 acc": 0.15728, "top5 acc": 0.39598}
{"mode": "train", "epoch": 76, "iter": 10, "lr": 1e-05, "time": 3.32185, "data_time": 1.80042, "memory": 16456, "loss_cls": 3.65256, "loss": 3.65256}
{"mode": "val", "epoch": 76, "iter": 19, "lr": 1e-05, "top1 acc": 0.16283, "top5 acc": 0.40338}
{"mode": "train", "epoch": 77, "iter": 10, "lr": 1e-05, "time": 3.49864, "data_time": 1.92502, "memory": 16456, "loss_cls": 3.69327, "loss": 3.69327}
{"mode": "val", "epoch": 77, "iter": 19, "lr": 1e-05, "top1 acc": 0.16178, "top5 acc": 0.40021}
{"mode": "train", "epoch": 78, "iter": 10, "lr": 1e-05, "time": 3.15994, "data_time": 1.54278, "memory": 16456, "loss_cls": 3.62659, "loss": 3.62659}
{"mode": "val", "epoch": 78, "iter": 19, "lr": 1e-05, "top1 acc": 0.16098, "top5 acc": 0.40127}
{"mode": "train", "epoch": 79, "iter": 10, "lr": 1e-05, "time": 3.21483, "data_time": 1.69456, "memory": 16456, "loss_cls": 3.68016, "loss": 3.68016}
{"mode": "val", "epoch": 79, "iter": 19, "lr": 1e-05, "top1 acc": 0.16098, "top5 acc": 0.3944}
{"mode": "train", "epoch": 80, "iter": 10, "lr": 1e-05, "time": 3.42626, "data_time": 1.96745, "memory": 16456, "loss_cls": 3.6863, "loss": 3.6863}
{"mode": "val", "epoch": 80, "iter": 19, "lr": 1e-05, "top1 acc": 0.15993, "top5 acc": 0.39598}

**Comment by walton-wang929** [comment]
after 80 epochs, the "top1 acc": 0.15993, "top5 acc": 0.39598 .

**Comment by walton-wang929** [comment]
I also tested with test_recognizer.py, the result was samely bad:

Averaging score over 1 clips without softmax (ie, raw)
Mean Class Accuracy = 16.49
Top-1 Accuracy = 17.08
Top-5 Accuracy = 41.16

compared with your provided model:
Averaging score over 1 clips without softmax (ie, raw)
Mean Class Accuracy = 61.88
Top-1 Accuracy = 62.70
Top-5 Accuracy = 84.56

**Comment by walton-wang929** [comment]
I used 4 gpus, modified videos_per_gpu=32, and  workers_per_gpu=2, to  videos_per_gpu=128 and workers_per_gpu=4,  then calculate the new lr=0.032

**Comment by walton-wang929** [comment]
I used 4 gpus, modified videos_per_gpu=32, and workers_per_gpu=2, to videos_per_gpu=128 and workers_per_gpu=4, then calculate the new lr=0.002

**Comment by walton-wang929** [comment]
@bryanyzhu can you open this issue again?

**Comment by bryanyzhu** [comment]
@walton-wang929 I think it's better for you to open a new issue because our issues are different. Your training log seems weird, especially the first loss. 70+ loss is clearly wrong, the maximum loss should be around 5. Your model may not be initialized well in the beginning.
