### ISSUE TITLE
support InceptionV1_I3D pretrained on Kinetics-400

### ISSUE THREAD

**Issue by leaderj1001** [open-mmlab/mmaction#132]
Hi, I'm Myeongjun Kim.

Can we available the inception I3D network pretrained on Kinetics-400?
Thank you.

**Comment by zhaoyue-zephyrus** [comment]
Hi @leaderj1001 

Please take a look at the most recent update. We have ported  the official model in TensorFlow (https://github.com/deepmind/kinetics-i3d) to PyTorch.

Yue
