### ISSUE TITLE
Possible memory leak for tvl1 optical flow computation via the script build_rawframes.py

### ISSUE THREAD

**Issue by atique81** [open-mmlab/mmaction#136]
Hello,

I noticed that, while extracting optical flow (tvl1) using the script build_rawframes.py, the RAM consumption keeps going up and up and at some point the process occupies all of the available RAM and then gets killed by OOM. It happens no matter how many workers you use, how many videos you extract optical flow for. I am not sure if it is the issue coming from dense_flow or somewhere else. 

Can you please comment?

**Comment by odefiao** [comment]
I do not find the problem you mentioned. but, Can you tell me the speed of your optical flow (tvl1) extract? I test only 1 video with 3075 frames, and it cost 13 minutes on opencv4.1.0 v100(32G).
`dense_flow-opencv-4.1.0/build/extract_gpu -f=test/v_zz3Mw8FMA70.mp4 -x=test_extract/v_zz3Mw8FMA70/flow_x -y=/test_extract/v_zz3Mw8FMA70/flow_y -i=test_extract/v_zz3Mw8FMA70/img -b=20 -t=1 -d=0 -s=1 -o=dir -w=340 -h=256`

**Comment by atique81** [comment]
Hello @odefiao ,
Thanks for getting back. For me, a video with 18,283 frames (512x384) took around 3 hours on a TitanXp gpu (12 Gigs) with OpenCV4.1.0 and  64Gigs RAM . The problem shows up when I run multiple sessions of build_rawframes.py, where each session uses multiple workers to extract rgb+flow frames from several videos. In such a situation the RAM consumption gradually keeps increasing (though there is GPU memory available). That's why, I thought that there might be some memory leak.

**Comment by chenjiadong96** [comment]
Hello @atique81 ，
How do you use build_rawframes.py?
When I execute            python build_rawframes.py / home / gpuserver06 / mmaction / data / DATASET home / gpuserver06 / mmaction / data / DATASET / rawframes --df_path / home / gpuserver06 / mmaction / third_party / dense_flow --level 2,          no errors are generated . But the folder of the output path is empty。
![image](https://user-images.githubusercontent.com/65204425/83366931-9d96d400-a3e4-11ea-88c2-26f19f674d46.png)
![image](https://user-images.githubusercontent.com/65204425/83366935-a4bde200-a3e4-11ea-8083-15f7a189537b.png)

**Comment by kennymckormick** [comment]
We recommend using our [new version of denseflow](https://github.com/open-mmlab/denseflow), which is more efficient and easy to install. You can use [setup](https://github.com/innerlee/setup) to easily install all requirements(Thanks @innerlee for the contribution).
