### ISSUE TITLE
running “python build_rawframes.py...”，error ：name 'args' is not defined

### ISSUE THREAD

**Issue by xianguo-dev** [open-mmlab/mmaction#139]
I was runnig the code“D:\github\mmaction-master\data_tools>python build_rawframes.py D:\github\mmaction-master\data\drink\SRC_FOLDER D:\github\mmaction-master\data\drink\OUT_FOLDER --df_path C:\Users\29684\dense_flow --level  1”to get frames while there was a error.Details are as follows：
  D:\github\mmaction-master\data_tools>python build_rawframes.py D:\github\mmaction-master\data\drink\SRC_FOLDER D:\github\mmaction-master\data\drink\OUT_FOLDER --df_path C:\Users\29684\dense_flow --level  1
Reading videos from folder:  D:\github\mmaction-master\data\drink\SRC_FOLDER
Extension of videos:  avi
Total number of videos found:  3
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "D:\anaconda\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "D:\anaconda\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "D:\github\mmaction-master\data_tools\build_rawframes.py", line 15, in dump_frames
    out_full_path = osp.join(args.out_dir, vid_name)
NameError: name 'args' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build_rawframes.py", line 159, in <module>
    fullpath_list, vid_list, range(len(vid_list))))
  File "D:\anaconda\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "D:\anaconda\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
NameError: name 'args' is not defined

I‘m so thankful for your generals help ，which contributes to my work significantly，but could you please help me deal with that problem？’

**Comment by xianguo-dev** [comment]
I was running at windows cmd，maybe I must run it in linux？

**Comment by zhaoyue-zephyrus** [comment]
Hi @xianguo-dev 

Sorry this repo has no support for Windows. You may have to run it on Linux.

Yue

**Comment by xianguo-dev** [comment]
Thanks for your reply，I‘d like to try ur code on unbuntu！Hope it‘ll work then.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Yue Zhao"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上10:33
收件人:&nbsp;"open-mmlab/mmaction"<mmaction@noreply.github.com&gt;;
抄送:&nbsp;"鲜果"<1009927879@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [open-mmlab/mmaction] running “python build_rawframes.py...”，error ：name 'args' is not defined (#139)





 
Hi @xianguo-dev
 
Sorry this repo has no support for Windows. You may have to run it on Linux.
 
Yue
