### ISSUE TITLE
Test Error. KeyError: 'bninception_caffe'.

### ISSUE THREAD

**Issue by hkkevinhf** [open-mmlab/mmaction#14]

**Comment by osmarcedron** [comment]
Hi @hkkevinhf, I was dealing with the same error,  I guess you used pip (seem a few commits behind master). I solved this by cloning mmcv (https://github.com/open-mmlab/mmcv) and install it in development mode. Cheers!

**Comment by zhaoyue-zephyrus** [comment]
Hi @hkkevinhf ,

(Seems that some guy has answered this issue but the comment is gone.)

Are you installing mmcv from pip? The models are new and haven't been published in the latest release. Please clone mmcv from https://github.com/open-mmlab/mmcv and build it from dev mode. Thanks!
