### ISSUE TITLE
Trying: Inference with pretrained models, getting the error below.

### ISSUE THREAD

**Issue by akashsharma29** [open-mmlab/mmaction#145]
I am trying to test the "Inference with pre-trained models", on the MMaction documentation. I am getting the error below:

python tools/test_recognizer.py --local_rank=0 --launcher pytorch tsn_rgb_bninception.py ./modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 

![Github1](https://user-images.githubusercontent.com/36917739/77195972-849ea800-6ab0-11ea-9a6c-89aa90ef856e.png)

If anyone faced this or a similar issue, let me know. Thanks

**Comment by akashsharma29** [comment]
@yjxiong @loveunk @acrophile @lindahua

**Comment by loveunk** [comment]
You can try with `dist_test_recognizer.sh`.

An example:
```bash
./tools/dist_test_recognizer.sh \
  configs/ucf101/tsn_flow_bninception.py \
  ./work_dirs/ucf101/tsn_2d_flow_bninception_seg_3_f1s1_b32_g8_lr_0.005/latest.pth 2 \
  --out ./work_dirs/ucf101/tsn_2d_flow_bninception_seg_3_f1s1_b32_g8_lr_0.005/result.pkl
```

**Comment by kennymckormick** [comment]
@loveunk is right. You need to use dist_test_recognizer.sh for testing.
