### ISSUE TITLE
Backbone "ResNet_3D" in test_configs/CSN does not exist

### ISSUE THREAD

**Issue by caidonkey** [open-mmlab/mmaction#148]
Thanks for providing this comprehensive code base. 
When I tried to evaluate the newly updated model "CSN" and "R2plus1D", I found the backbones specified in corresponding config. files (test_configs/*.py ) were "ResNet_3D". However, there are no such backbone supported, as listed below:
    'BNInception',
    'ResNet',
    'InceptionV1_I3D',
    'ResNet_I3D',
    'ResNet_S3D',
    'ResNet_I3D_SlowFast',
    'ResNet_R3D'

I modified the backbone to any of the above "ResNet_*3D", all came out to show errors. Would you help update the corresponding backbone files? Thanks a lot.

**Comment by kennymckormick** [comment]
Sorry, it should be ResNet_R3D, and we will fix it. Would you please tell me what is the error when you replace 'ResNet_3D' with 'ResNet_R3D'?

**Comment by caidonkey** [comment]
> Sorry, it should be ResNet_R3D, and we will fix it. Would you please tell me what is the error when you replace 'ResNet_3D' with 'ResNet_R3D'?

Thanks for your reply. In this case, the error can be easily fixed by adding "import numpy as np" at the beginning of "ResNet_R3D.py". :)

**Comment by liu666666** [comment]
Thanks. @caidonkey I add  "import numpy as np" and run it successfully, but I meet the following warning and get a very low performance. Do you know how to fix this warning? Thank you!

2020-05-01 18:52:37,683 - WARNING - The model and loaded state dict do not match exactly

size mismatch for backbone.layer1.a.conv1.conv_C.weight: copying a param with shape torch.Size([64, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3, 3]).
size mismatch for backbone.layer1.b.conv1.conv_C.weight: copying a param with shape torch.Size([64, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3, 3]).
size mismatch for backbone.layer1.c.conv1.conv_C.weight: copying a param with shape torch.Size([64, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([64, 64, 3, 3, 3]).
size mismatch for backbone.layer2.a.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.b.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.c.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.d.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.e.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.f.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.g.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer2.h.conv1.conv_C.weight: copying a param with shape torch.Size([128, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 128, 3, 3, 3]).
size mismatch for backbone.layer3.aa.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ab.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ac.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ad.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ae.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.af.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ag.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ah.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ai.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.aj.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ak.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.al.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.am.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.an.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ao.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ap.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.aq.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ar.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.as.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.at.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.au.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.av.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.aw.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ax.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ay.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.az.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.ba.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bb.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bc.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bd.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.be.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bf.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bg.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bh.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bi.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer3.bj.conv1.conv_C.weight: copying a param with shape torch.Size([256, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([256, 256, 3, 3, 3]).
size mismatch for backbone.layer4.a.conv1.conv_C.weight: copying a param with shape torch.Size([512, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3, 3]).
size mismatch for backbone.layer4.b.conv1.conv_C.weight: copying a param with shape torch.Size([512, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3, 3]).
size mismatch for backbone.layer4.c.conv1.conv_C.weight: copying a param with shape torch.Size([512, 1, 3, 3, 3]) from checkpoint, the shape in current model is torch.Size([512, 512, 3, 3, 3]).
