### ISSUE TITLE
no response when extract the flow images

### ISSUE THREAD

**Issue by semchan** [open-mmlab/mmaction#149]
Dear, I follow the guide to install denseflow and opencv with no error, but when I use the cmd , there is no response, no error, no report and no images out. BWT, I use two GPUs. Would you please help me? thanks a lot

./extract_gpu -f=v_0AbJgWxIYVI.mp4 -x=tmp/flow_x -y=tmp/flow_y -i=tmp/image -b=20 -t=1 -d=0 -s=1 -o=dir

**Comment by rezaghoddoosian** [comment]
I have the same issue, when my arg.number_of_workers is more than 1 I get error, but when I set it to 1, it faces the same issue you say. Still working on it.

**Comment by kennymckormick** [comment]
We recommend using our [new version of denseflow](https://github.com/open-mmlab/denseflow), which is more efficient and easy to install. You can use [setup](https://github.com/innerlee/setup) to easily install all requirements.
