### ISSUE TITLE
Install Opencv = 4.1.0 failed

### ISSUE THREAD

**Issue by yutan1997** [open-mmlab/mmaction#151]
Ubuntu 16.04
ffmpeg:4.2.2
cmake: 3.8.2
gcc: 5.4.0
CUDA: 9.0
During Step 3 Build OpenCV 4.1.0 from scratch (due to some custom settings)
when executing
"cmake -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules/ -DWITH_TBB=ON -DBUILD_opencv_cnn_3dobj=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_dnn_modern=OFF -DBUILD_opencv_dnns_easily_fooled=OFF -DOPENCV_ENABLE_NONFREE=ON ..
"
it turns out that 
"
-- Configuring incomplete, errors occurred!
See also "/media/shechen/workspace/mmaction/third_party/opencv-4.1.0/build/CMakeFiles/CMakeOutput.log".
See also "/media/shechen/workspace/mmaction/third_party/opencv-4.1.0/build/CMakeFiles/CMakeError.log".
"
when I turn to CMakeError.log
**/media/shechen/workspace/mmaction/third_party/opencv-4.1.0/build/CMakeFiles/CMakeTmp/CheckIncludeFile.c:1:25: fatal error: sys/videoio.h: No such file or directory
compilation terminated.
CMakeFiles/cmTC_2ec36.dir/build.make:65: recipe for target 'CMakeFiles/cmTC_2ec36.dir/CheckIncludeFile.c.o' failed
make[1]: *** [CMakeFiles/cmTC_2ec36.dir/CheckIncludeFile.c.o] Error 1
make[1]: Leaving directory '/media/shechen/workspace/mmaction/third_party/opencv-4.1.0/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2ec36/fast' failed
make: *** [cmTC_2ec36/fast] Error 2]**

When searching in google, I cannot find the answer. Is there anyone who met the same problem like me ?

**Comment by wzy1845** [comment]
same issue

**Comment by wzy1845** [comment]
`sudo cp /media/wzy/WZYPassport/mmaction/third_party/opencv-4.1.0/modules/videoio/include/opencv2/videoio/videoio_c.h  /usr/include/x86_64-linux-gnu/sys
`
`sudo ln -s /usr/include/x86_64-linux-gnu/sys/videoio_c.h  /usr/include/x86_64-linux-gnu/sys/videoio.h
`
`cmake -DCUDA_nppi_LIBRARY=true -DBUILD_TIFF=ON -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules/ -DWITH_TBB=ON -DBUILD_opencv_cnn_3dobj=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_dnn_modern=OFF -DBUILD_opencv_dnns_easily_fooled=OFF -DOPENCV_ENABLE_NONFREE=ON ..`

**Comment by kennymckormick** [comment]
You can use [setup](https://github.com/innerlee/setup) to easily install opencv and denseflow.
