### ISSUE TITLE
Install Denseflow failed. CMake Error: Parse error in cache file ../CMakeCache.txt on line 313. Offending entry: /*

### ISSUE THREAD

**Issue by spyflying** [open-mmlab/mmaction#154]
**Environment: Opencv-2.4.13, cuda-8.0, cmake-3.8, gcc-5.4, ffmpeg-4.2.1**

**When I execute `make -j`, it comes out that**

CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 313. Offending entry: /*
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 314. Offending entry: zipconf.h -- platform specific include file
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 316. Offending entry: This file was generated automatically by CMake
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 317. Offending entry: based on ../cmake-zipconf.h.in.
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 318. Offending entry: */
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 325. Offending entry: /* #undef ZIP_STATIC */
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 333. Offending entry: typedef int8_t zip_int8_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 334. Offending entry: typedef uint8_t zip_uint8_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 335. Offending entry: typedef int16_t zip_int16_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 336. Offending entry: typedef uint16_t zip_uint16_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 337. Offending entry: typedef int32_t zip_int32_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 338. Offending entry: typedef uint32_t zip_uint32_t;
CMake Error: Parse error in cache file mypath/dense_flow/build/CMakeCache.txt on line 339. Offending entry: typedef int64_t zip_int64_t;
CMake Error: Parse error in cache file 
mypath/dense_flow/build/CMakeCache.txt on line 340. Offending entry: typedef uint64_t zip_uint64_t;
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   python
-- Configuring incomplete, errors occurred!
See also "mypath/dense_flow/build/CMakeFiles/CMakeOutput.log".
See also "mypath/dense_flow/build/CMakeFiles/CMakeError.log".

**Anyone came across with the same error with me?**

**Comment by kennymckormick** [comment]
We recommend using our [new version of denseflow](https://github.com/open-mmlab/denseflow), which is more efficient and easy to install. You can use [setup](https://github.com/innerlee/setup) to easily install all requirements(Thanks @innerlee for the contribution).
