### ISSUE TITLE
MMaction for custom video dataset

### ISSUE THREAD

**Issue by rashidch** [open-mmlab/mmaction#155]
Hey,

Thanks for awesome code base on action recognition.

Can you kindly tell the steps to prepare custom dataset for training mmaction?

**Comment by kennymckormick** [comment]
Assume you have a trimmed labeled video dataset( (vid1.mp4, label1), (vid2.mp4, label2), ..., (vidN.mp4, labelN) ) and you want to train trimmed video recognition. If you use VideoDataset, you can generate a list looks like: 

vid1.mp4 label1
vid2.mp4 label2
...
vidN.mp4 labelN

If you use RawframeDataset, you need to first use ffmpeg or denseflow to extract frames, extracted frames look like vid1/img_00001.jpg, vid1/img_00002.jpg, ... , assume vidN.mp4 has numN extracted frames, your list should look like:

vid1 num1 label1
vid2 num2 label2
...
vidN numN labelN
