### ISSUE TITLE
Question on data augmentation

### ISSUE THREAD

**Issue by bryanyzhu** [open-mmlab/mmaction#157]
Hi, I was reading the config file of SlowOnly model on K400. There are two parameters that are confusing me. 

https://github.com/open-mmlab/mmaction/blob/7505a59535649c05a80bbea738c7019d0b58fe15/configs/SlowOnly/slowonly_kinetics400_se_rgb_r50_seg1_8x8_scratch.py#L63-L68

As you can see, the `resize_crop` is True, and `multiscale_crop ` is also True. Then how do you decide which crop_op you are using at here? 

https://github.com/open-mmlab/mmaction/blob/7505a59535649c05a80bbea738c7019d0b58fe15/mmaction/datasets/transforms.py#L402-L408

Since you have two `True` in an if-else control flow. Thank you.

**Comment by kennymckormick** [comment]
Hi, bryanyzhu. In the code, when resize_crop is set to be True, it overrides multiscale_crop. We are using resize_crop here.
