### ISSUE TITLE
Legacy Autograd function warnings

### ISSUE THREAD

**Issue by cinjon** [open-mmlab/mmaction#163]
Hi, I am getting a lot of these warnings when using the TSN2d config from kinetics.

`/opt/conda/conda-bld/pytorch_1579022027550/work/torch/csrc/autograd/python_function.cpp:622: UserWarning: Legacy autograd function with non-static forward method is deprecated and will be removed in 1.3. Please use new-style autograd function with static forward method. (Example: https://pytorch.org/docs/stable/autograd.html#torch.autograd.Function)`

It seems to be related to some function being static when it shouldn't be. I don't see where this could be though in the pipeline. Help?

**Comment by BestJuly** [comment]
Please check #101. The solution provided by @loveunk helped me with the same problem.

**Comment by zhaoyue-zephyrus** [comment]
This issue should be fixed in this PR https://github.com/open-mmlab/mmaction/pull/196.
