### ISSUE TITLE
a question about BN-Inception, the ReLU does not work in this code

### ISSUE THREAD

**Issue by 232525** [open-mmlab/mmaction#164]
Hello, when I try to use the code of [BNInception ](https://github.com/open-mmlab/mmaction/blob/21e4234da73cfd6dd5b1cfbffdf94141cd27e2a5/mmaction/models/tenons/backbones/bninception.py),  I found some confusing questions. In Inception, one basic Conv unit contains \{**Conv2d** layer, **BatchNorm** layer and **ReLU**\}, when there are two Conv unit stacked, the input of second unit should be the **ReLU** output of the first unit, but in [here](https://github.com/open-mmlab/mmaction/blob/21e4234da73cfd6dd5b1cfbffdf94141cd27e2a5/mmaction/models/tenons/backbones/bninception.py), is **BatchNorm** output.  So actually, the ReLU activate function does not work.

For example, the line [281 ](https://github.com/open-mmlab/mmaction/blob/21e4234da73cfd6dd5b1cfbffdf94141cd27e2a5/mmaction/models/tenons/backbones/bninception.py#L281)to 284, 
```
inception_3a_3x3_reduce_out = self.inception_3a_3x3_reduce(pool2_3x3_s2_out)
inception_3a_3x3_reduce_bn_out = self.inception_3a_3x3_reduce_bn(inception_3a_3x3_reduce_out)
inception_3a_relu_3x3_reduce_out = self.inception_3a_relu_3x3_reduce(inception_3a_3x3_reduce_bn_out)
inception_3a_3x3_out = self.inception_3a_3x3(inception_3a_3x3_reduce_bn_out)
```
I think the input to `self.inception_3a_3x3` should be `inception_3a_relu_3x3_reduce_out`  instead of `inception_3a_3x3_reduce_bn_out`

Look forward to your reply!

**Comment by zhaoyue-zephyrus** [comment]
@232525 
Hi, we use `in_place=True` (https://github.com/open-mmlab/mmaction/blob/master/mmaction/models/tenons/backbones/bninception.py#L28). Therefore using either is equivalent.
