### ISSUE TITLE
Outdated Dockerfile

### ISSUE THREAD

**Issue by escorciav** [open-mmlab/mmaction#166]
Hi!

It seems that the python version of the Dockerfile is too old for the f-string syntax used in another library.

```
$ bash extracted_frames.sh Traceback (most recent call last):
  File "build_rawframes.py", line 9, in <module>    import mmcv
  File "/data/mmcv/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  File "/data/mmcv/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "/data/mmcv/mmcv/arraymisc/quantization.py", line 20
    f'levels must be a positive integer, but got {levels}')
                                                         ^
SyntaxError: invalid syntax
Raw frames (RGB and tv-l1) Generated for val setTraceback (most recent call last):
  File "build_rawframes.py", line 9, in <module>    import mmcv
  File "/data/mmcv/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  File "/data/mmcv/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "/data/mmcv/mmcv/arraymisc/quantization.py", line 20
    f'levels must be a positive integer, but got {levels}')
                                                         ^
SyntaxError: invalid syntax
Raw frames (RGB and tv-l1) Generated for test set
I have no name!@345e74d5b930:/home/SERILOCAL/v.castillo/projects/3rdparty/mmaction/data_tools/thumos14$ python3
Python 3.5.2 (default, Apr 16 2020, 17:47:17) 
[GCC 5.4.0 20160609] on linuxType "help", "copyright", "credits" or "license" for more information.
>>>
```

BTW, thanks for providing this tool very much needed for video understanding.

**Comment by escorciav** [comment]
In case, anyone else faces the issue check out the references below:

- use ppa mentioned [here](https://askubuntu.com/a/865569).

- To make python3.6 the default choice use the trick mentioned [here](http://ubuntuhandbook.org/index.php/2017/07/install-python-3-6-1-in-ubuntu-16-04-lts/).

I let the image building, might report later :)

**Comment by escorciav** [comment]
kinda work it got stuck building `mmcv`

I found this relevant bit from a very long traceback

```
./mmcv/video/optflow_warp/flow_warp_module.cpp:4:20: fatal error: Python.h: No such file or directory
```

Any help would be welcome.

**Comment by escorciav** [comment]
mmm, it seems that the ppa does not include python development stuff 😞

**Comment by escorciav** [comment]
Latest status: I plan to add python3.6 using pyenv as mentioned [here](https://askubuntu.com/a/865644)

Before that, I plan to give a shot to any of the [mmaction images in dockerhub](https://hub.docker.com/search?q=mmaction&type=image). Perhaps, it won't work as I did manage to build an image without issues however they might have built it before mmcv move to python>= 3.6+

**Comment by escorciav** [comment]
To save you time, if you are need `mmaction/third_party/dense_flow/build/extract_gpu`

(Today) these images: [mlouieunm](https://hub.docker.com/r/mlouieunm/mmaction), [martjushev](https://hub.docker.com/r/martjushev/mmaction) won't help :)

It looks like the one with the least number of ⭐ could. It looks like the person uses conda and added detectron2 and slowfast among other things.

**Comment by escorciav** [comment]
and nope the last image is still WIP 😫  ... it might be a good starting point but without the Dockerfile is hard to tell. Hopefully, I was taking a look at the [pyenv](https://github.com/pyenv/pyenv) in the background. I even received guidance from a sibling [project](https://github.com/pyenv/pyenv-installer/issues/98#issuecomment-621221494)

can't say the same about the maintainers of this project as they haven't appeared yet 😆 . 🤞  they are healthy and just busy with other duties.

**Comment by Pr0duktiv** [comment]
Try `pip install mmcv==0.2.16` after building and starting the Dockerfile from this repository

**Comment by escorciav** [comment]
are u kidding me? was it a single command?

I managed to plugin pyenv and build everything, except for `decord`, yesterday.

**Comment by Pr0duktiv** [comment]
Yeah it was a single command for me, I had the same issue as you. I might just do a pull request that fixes this in the Dockerfile if the maintainers merge it.

**Comment by escorciav** [comment]
omg, thk for sharing. Honestly, it would be cool to fix the requirements. Please do that if you submit a PR 🙏 

I have seen the same patterns in other projects (cloudcv@evalai). People "dockerize" but don't fix the dependencies, the outcome Docker is useless. As it's the case here, the developers aren't kind to push an image to dockerhub.

I wish academics take one year of their PhD, to learn software engineering workflow associated with reproducibility and replicability.

**Comment by yjxiong** [comment]
The developers are busy with other projects right now. Your PR of the solution is welcome.

**Comment by yjxiong** [comment]
@escorciav 

I really recommend you to read the [LICENSE](https://github.com/open-mmlab/mmaction/blob/master/LICENSE) of this code repo. Being sarcastic against other people spending actual time and efforts does not really do you any good.

**Comment by escorciav** [comment]
Thanks @yjxiong for stepping in (not sarcasm)

I believe _there is a misunderstanding_ as I clearly expressed my gratefulness with the core-developers since the first message. I feel that the disappointment of not getting the things to work could have influenced the way that I express myself leading to this. Thus,

**I'm truly sorry**. When I said that I hope you are safe and healthy, I truly mean that. We are living tough times, thus anytime that I don't receive an answer from anyone I only hope that the receiver is busy as no one is immune to be stroked by this.

I hope you can accept my apologies. I respect your career, and you have been truly kind when we have interacted by email in the past. This in on you now, if you feel that I haven't done enough please let me know.

Cheers,
Victor

**Comment by Pr0duktiv** [comment]
You can close this issue I think @escorciav

**Comment by escorciav** [comment]
In case anyone want to update python... I did some progress with [pyenv](https://github.com/pyenv/pyenv).

It allows us to use a python version different from the one of the system. `pyenv` is similar to `rbenv` in Ruby.

Check out the branch `docker-pyenv` in my [mmaction-fork](https://github.com/escorciav/mmaction/tree/docker-pyenv)
