### ISSUE TITLE
Torch cuda issue 

### ISSUE THREAD

**Issue by abhiagwl4262** [open-mmlab/mmaction#168]
Hey, 

I am getting this error -     

File "/data/mmaction/mmaction/apis/env.py", line 29, in _init_dist_pytorch
torch.cuda.set_device(rank % num_gpus)
ZeroDivisionError: integer division or modulo by zero

This is because "torch.cuda.is_available() is giving False ". what does that mean?

Though result of nvcc --version is - 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176

**Comment by zhaoyue-zephyrus** [comment]
check the torch' cuda version and your driver version to see if they match.
