### ISSUE TITLE
how to non dist test,thank you!

### ISSUE THREAD

**Issue by 864546664** [open-mmlab/mmaction#171]
i have only one gpu,and i have trainde my own dataset on tsn2d,but when i tried to test my data,
Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 180, in <module>
    main()
  File "./tools/test_recognizer.py", line 149, in main
    dist=distributed,
UnboundLocalError: local variable 'distributed' referenced before assignment

i want to know how to solve it ,thank you very much!!!

**Comment by loveunk** [comment]
@864546664 what's your training command?

**Comment by 864546664** [comment]
> @864546664 what's your training command?

感谢回答，我已经自己改好了

**Comment by PhyllisH** [comment]
请问答主怎么改的呀？

**Comment by 864546664** [comment]
> 请问答主怎么改的呀？

训练文件单卡是没问题的，把测试文件里报错的地方用训练文件里的语句替代就行了

**Comment by kennymckormick** [comment]
It's OK to use distributed test if u only have one gpu, just set the nproc_per_node to be 1 in dist_test_recognizer.sh

**Comment by Cli98** [comment]
> It's OK to use distributed test if u only have one gpu, just set the nproc_per_node to be 1 in dist_test_recognizer.sh

If we are required to conduct online-testing, the time to call one gpu for dist testing is time costing. So it is still necessary to provide non-dist version
