### ISSUE TITLE
Run action recognition model on mobile

### ISSUE THREAD

**Issue by stereomatchingkiss** [open-mmlab/mmaction#173]
According to your [paper](https://arxiv.org/pdf/1906.07052.pdf), you run the action recognition model with tflite, if I want to perform action recognition on mobile(android, like mate30) too, which model you would recommend(Smallest TSN model from the model zoo)?

Do you perform quantization before you run the model on the mobile?Have you tried to run the model on android by pytorch?

Thanks

**Comment by yjxiong** [comment]
Hi, this is not our paper. 

This framework is based on Pytorch, not tensorflow as in the paper. We haven't tried running models on mobile devices. You may look at TVM for quantization and model deployment. Or you can consult the authors of the paper.
