### ISSUE TITLE
A problem about the pretrained models: https://github.com/open-mmlab/mmaction/blob/master/MODEL_ZOO.md

### ISSUE THREAD

**Issue by chenxlin222** [open-mmlab/mmaction#178]
Hi,
Thanks for the wonderful work. I am a green hand in this field, and I have downloaded the pre-trained models you provided. But I have a problem, I didn't find the "TV-L1 Modality" pre-trained on Kinetics400 with resnet50.. Are the RGB stream and Flow stream share the same weights (RGB Modality) as pre-trained params? 

PS: However, the BNinception pre-trained on Imagenet has two Modality, RGB Modality and TV-L1 Modality.
https://github.com/open-mmlab/mmaction/blob/master/MODEL_ZOO.md

Very sorry to trouble you with this problem. Looking forward to your reply. Thanks very much!

**Comment by chenxlin222** [comment]
can anyone help me? Thanks very much!

**Comment by kennymckormick** [comment]
When we train models with TVL1 modality, we can use the ImageNet pre-trained weights as initialization. The performance will be better than the default initialization. Currently, we only release I3D weights trained with Kinetics400, we will release "TV-L1 Modality" pre-trained on Kinetics400 with R50(2D / 3D) soon.

**Comment by talhaubaid** [comment]
@chenxlin222 can you please share the model weights as they have removed the weights from zoo.model files.
