### ISSUE TITLE
other service can't use the GPU again!

### ISSUE THREAD

**Issue by ImageWPro** [open-mmlab/mmaction#179]
@yjxiong @loveunk @acrophile @plbecker hello , thank you for you nice job.
now I have some troubles. I follow you guide can run the TSN with "bash extract_frames.sh" to extract rgb frames and optical flow successful, and they can use the GPUs（Tesla V100）, I have 2 GPUs and set 6 number works. Cuda version is 10.0. every GPU only use the 50% almost.
The problem has occur. when I want to run other service with  GPU, they can run but can't use the GPU again, they only use the CPU resource.  before I use your job, they can use GPU normaly. 
could you tell me the reason and how to solve it.

**Comment by yjxiong** [comment]
I don't know what is wrong and what is the error message you got. 

I think you can measure how much GPU memory your other service needs and see if they fit in the memory size your GPUs have.
