### ISSUE TITLE
how to just extract frames not optical flow

### ISSUE THREAD

**Issue by isalirezag** [open-mmlab/mmaction#18]
in  mmaction/data_tools/thumos14/extracted_frames.sh we can extract both frame and optical-flow via `python build_rawframes.py ../data/thumos14/videos_val/ ../data/thumos14/rawframes/ --level 1 --flow_type tvl1 --ext mp4`
how can I change the command above to just extract the frame and not optical flow?
Thanks

**Comment by isalirezag** [comment]
also can you please explain what do you mean by single and two level in 
`--level is either 1 for the single-level directory or 2 for the two-level directory`

**Comment by zhangluustb** [comment]
@isalirezag 
`python build_rawframes.py ../data/ucf101/videos/ ../data/ucf101/rawframes/ --level 2`

**Comment by zhangluustb** [comment]
> also can you please explain what do you mean by single and two level in
> `--level is either 1 for the single-level directory or 2 for the two-level directory`

`if args.level == 2:
        fullpath_list = glob.glob(args.src_dir + '/*/*.' + args.ext)
        done_fullpath_list = glob.glob(args.out_dir + '/*/*')
    elif args.level == 1:
        fullpath_list = glob.glob(args.src_dir + '/*.' + args.ext)
        done_fullpath_list = glob.glob(args.out_dir + '/*')`
means the different imageSet dir structures.

**Comment by zhaoyue-zephyrus** [comment]
@isalirezag please refer to @zhangluustb 's comments. Thank you, @zhangluustb !

**Comment by isalirezag** [comment]
@zhangluustb  where is function `build_rawframes`, i need to change the avi to mp4 apparently.
