### ISSUE TITLE
 No module named 'mmcv.parallel.distributed_deprecated'

### ISSUE THREAD

**Issue by Amazingren** [open-mmlab/mmaction#183]
After following the instruction of  '' Install.md'' and " Getting Started", I want to have a try this codebase for action recognition on UCF101,
But when I step in testing the model downloaded from modelzoo with the following commend:
`./tools/dist_test_recognizer.sh test_configs/TSN/ucf101/tsn_rgb_bninception.py modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth 4`
It occurs the errors as follows:
`Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 16, in <module>
    from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel
ModuleNotFoundError: No module named 'mmcv.parallel.distributed_deprecated'
Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 16, in <module>
    from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel
ModuleNotFoundError: No module named 'mmcv.parallel.distributed_deprecated'
Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 16, in <module>
    from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel
ModuleNotFoundError: No module named 'mmcv.parallel.distributed_deprecated'
Traceback (most recent call last):
  File "./tools/test_recognizer.py", line 16, in <module>
    from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel
ModuleNotFoundError: No module named 'mmcv.parallel.distributed_deprecated'
Traceback (most recent call last):
  File "/home/renb/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/renb/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/renb/anaconda3/lib/python3.7/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/renb/anaconda3/bin/python', '-u', './tools/test_recognizer.py', '--local_rank=0', 'test_configs/TSN/ucf101/tsn_rgb_bninception.py', 'modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth', '--launcher', 'pytorch']' returned non-zero exit status 1.
`
I have also tried to reinstall mmcv through `pip install mmcv`, then use ipython for test:
![微信截图_20200706011630](https://user-images.githubusercontent.com/31409716/86538116-83da3680-bf26-11ea-8016-d04bddcecee9.png)

How could I fix this, thanks for your time~

**Comment by Amazingren** [comment]
Is there anybody else who has the same problem?

**Comment by zhaoyue-zephyrus** [comment]
Hi @Amazingren, would you please try `pip install mmcv==0.3.0` to see if it works? MMCV has gone through several changes.

**Comment by Amazingren** [comment]
> Hi @Amazingren, would you please try `pip install mmcv==0.3.0` to see if it works? MMCV has gone through several changes.
Thanks for the patience and your time. However, it still seems doesn't work for me, and the feedback is as follows:
![微信截图_20200707105833](https://user-images.githubusercontent.com/31409716/86697634-2686d800-c041-11ea-96f9-7a7a8ddcf34a.png)
Is this mean that the version is still incorrect?

**Comment by Amazingren** [comment]
> Hi @Amazingren, would you please try `pip install mmcv==0.3.0` to see if it works? MMCV has gone through several changes.

Hi @zhaoyue-zephyrus , I just fixed it by replacing 
`from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel
`
with
`from mmcv.parallel.distributed import MMDistributedDataParallel
`
in both test and train files, then it works! 
Thx all the same, and you can close this issue.

**Comment by zhaoyue-zephyrus** [comment]
@Amazingren Good to hear that.

**Comment by ajithvcoder** [comment]
if anyone wants mmcv, install it in this way 
pip install mmcv-full==1.0.5 -f https://download.openmmlab.com/mmcv/dist/cu101/torch1.3.0/index.html

look into https://mmcv.readthedocs.io/en/v1.3.15/get_started/installation.html bottom of page

**Comment by yaoweixiao-ux** [comment]
You can try replacing
`from mmcv.parallel.distributed_deprecated import MMDistributedDataParallel`
`dp_factory = {'cuda': MMDataParallel, 'cpu': MMDataParallel}`
with
`from mmengine.model.wrappers import MMDistributedDataParallel`
`dp_factory = {'cuda': MMDistributedDataParallel, 'cpu': MMDistributedDataParallel}`
