### ISSUE TITLE
extract_frame.sh run so slow!!

### ISSUE THREAD

**Issue by cediy2088** [open-mmlab/mmaction#205]
My machine has ten 1080TI Nvidia GPU,when I run extract_frame.sh with ucf101 dataset, it runs so slowly, it take 12 hours which only extract 5GB frames. Is it correct?

`Sat Aug  8 08:54:46 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.132                Driver Version: 390.132                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 26%   45C    P2    62W / 250W |    545MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:05:00.0 Off |                  N/A |
| 37%   64C    P2    67W / 250W |    396MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   2  GeForce GTX 108...  Off  | 00000000:06:00.0 Off |                  N/A |
| 30%   53C    P2    64W / 250W |    394MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   3  GeForce GTX 108...  Off  | 00000000:07:00.0 Off |                  N/A |
| 30%   52C    P2    61W / 250W |    394MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   4  GeForce GTX 108...  Off  | 00000000:08:00.0 Off |                  N/A |
| 29%   51C    P2    64W / 250W |    396MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   5  GeForce GTX 108...  Off  | 00000000:0B:00.0 Off |                  N/A |
| 31%   54C    P2    64W / 250W |    396MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   6  GeForce GTX 108...  Off  | 00000000:0C:00.0 Off |                  N/A |
| 33%   57C    P2    63W / 250W |    396MiB / 11178MiB |      1%      Default |
+-------------------------------+----------------------+----------------------+
|   7  GeForce GTX 108...  Off  | 00000000:0D:00.0 Off |                  N/A |
| 52%   59C    P2    65W / 265W |    396MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
|   8  GeForce GTX 108...  Off  | 00000000:0E:00.0 Off |                  N/A |
| 46%   77C    P2    86W / 250W |    631MiB / 11178MiB |     25%      Default |
+-------------------------------+----------------------+----------------------+
|   9  GeForce GTX 108...  Off  | 00000000:0F:00.0 Off |                  N/A |
| 41%   69C    P2    81W / 250W |    583MiB / 11178MiB |      2%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       990      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    0      1352      C   /usr/bin/python                              151MiB |
|    0     23698      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    1      6569      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    1     15248      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    2     13417      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    2     18784      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    3     26844      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    3     32011      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    4      3054      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    4     21966      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    5      5080      C   ...hird_party/dense_flow/build/extract_gpu   191MiB |
|    5     13970      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    6      4150      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    6     11288      C   ...hird_party/dense_flow/build/extract_gpu   193MiB |
|    7      3579      C   ...hird_party/dense_flow/build/extract_gpu   191MiB |
|    7     26039      C   ...hird_party/dense_flow/build/extract_gpu   191MiB |
`

**Comment by kennymckormick** [comment]
We recommend using our [new version of denseflow](https://github.com/open-mmlab/denseflow), which is more efficient and easy to install. You can use [setup](https://github.com/innerlee/setup) to easily install all requirements. We will update our extraction scripts soon.
