### ISSUE TITLE
something about model zoo

### ISSUE THREAD

**Issue by huamgmin** [open-mmlab/mmaction#207]
Hi, l have a problem about the R(2+1)D 's models given in model zoo .what's the mean of inputsize 8x8

**Comment by kennymckormick** [comment]
The meaning of 8x8 is 8(num of input frames) x 8(step size). For example, the 8 frames group [frame_1.jpg, frame_9.jpg, frame_17.jpg, ..., frame_57.jpg] is an 8x8 input.
