### ISSUE TITLE
Where can I find the mapping of index to class in kinetics 400?

### ISSUE THREAD

**Issue by RyanLiut** [open-mmlab/mmaction#209]
Hi,
    So grateful to the code!. I'd like to ask when can I find the index-to-class mapping in kinetics400?

    Thank you!

**Comment by zhaoyue-zephyrus** [comment]
Hi @RyanLiut 

The index is mapped to class names in *alphabetic* order.  You may as well check the code here: https://github.com/open-mmlab/mmaction/blob/master/mmaction/datasets/utils.py#L373.

**Comment by RyanLiut** [comment]
Thank you for your reply!
