### ISSUE TITLE
Could you please explain these parameters?

### ISSUE THREAD

**Issue by limingcv** [open-mmlab/mmaction#214]
Thanks for your contribution! I have read code but there are still some questions I can't understand.

The main question is the parameters to sample frames in `mmaction/datasets/rawframes_datasets.py`, from row 65 to row 72

```python
# parameters for frame fetching
# number of segments
self.num_segments = num_segments
# number of consecutive frames
self.old_length = new_length * new_step
self.new_length = new_length
# number of steps (sparse sampling for efficiency of io)
self.new_step = new_step
```

Could I understand it as following descriptions?

* The chosen video is divided into `num_segments` clips, each clip has `record.num_frames // num_segments` frames
* Sample `new_length` frame(s) in a clip, totally sampling `new_length * num_segments` frames for a video
* In a clip, sampling `new_length` frames with interval `new_step`

As a freshman, this really bother me a lot, I'm really appreciate it if you can help me!

Thanks again for your contribution!

**Comment by zhaoyue-zephyrus** [comment]
Hi @limingcv .

You are totally correct! BTW, `num_segments` is the notion from [TSN](https://arxiv.org/abs/1608.00859). For the 3DCNN-based methods, due to memory concerns, we just fix `num_segments` to be 1. In 2DCNN methods, `number of segments` being from 3 to 7 would be a good choice.

**Comment by limingcv** [comment]
Thanks a lot!
