### ISSUE TITLE
Could you please provide baidu disk link for some datasets?

### ISSUE THREAD

**Issue by limingcv** [open-mmlab/mmaction#215]
I'm here to ask questions again...

You know some datasets (Kinetics400, AV, etc) are difficult to download in Mainland China, which brings a lot of trouble to do research.

I tried to use other methods to download these data sets, but they all failed, so could you please provide another way to download these datasets?

I'd really appreciate it if you can answer me, thanks for your contribution again!

**Comment by zhaoyue-zephyrus** [comment]
Hi @limingcv,

For AVA, check here: https://github.com/cvdfoundation/ava-dataset

For Kinetics-400, we do keep a distribution on OneDrive, fill out the survey [here](https://docs.google.com/forms/d/e/1FAIpQLScPMuRI2QkYfQpaiFiRiDeoDmOx-0OgaseglHnAVodGXJC1IQ/viewform?usp=sf_link). For training, we do not have enough space to host them.

**Comment by limingcv** [comment]
Thanks a lot!

Yue Zhao <notifications@github.com> 于2020年10月16日周五 下午1:17写道：

**Comment by irvingzhang0512** [comment]
@limingcv 之前用迅雷能够下载AVA数据集，连接地址是上面个repo中 https://s3.amazonaws.com/ava-dataset/ 开头的

**Comment by limingcv** [comment]
@irvingzhang0512  收到, 感谢您回答, 请问您是否知道 Kinetics 400 的训练集在大陆要如何获取?

**Comment by irvingzhang0512** [comment]
> @irvingzhang0512 收到, 感谢您回答, 请问您是否知道 Kinetics 400 的训练集在大陆要如何获取?

闲鱼……我第一次看到的时候惊呆了，希望你喜欢

**Comment by irvingzhang0512** [comment]
> @irvingzhang0512 收到, 感谢您回答, 请问您是否知道 Kinetics 400 的训练集在大陆要如何获取?

当然，这显然是不合法的，我个人很不支持这种行为……我之前是找国外朋友下载的……

**Comment by limingcv** [comment]
> > @irvingzhang0512 收到, 感谢您回答, 请问您是否知道 Kinetics 400 的训练集在大陆要如何获取?
> 
> 当然，这显然是不合法的，我个人很不支持这种行为……我之前是找国外朋友下载的……

......谢谢

**Comment by limingcv** [comment]
@irvingzhang0512  请问您知道闲鱼那个数据集是完整的吗? 或者请问您现在还有这个数据集吗?
