### ISSUE TITLE
How to get the precision as high as you proposed in your benchmark when testing your model?

### ISSUE THREAD

**Issue by cecilia930426** [open-mmlab/mmaction#216]
I tested the model tsn_r50_320p_1x1x8_50e_activitynet_video_rgb in your benchmark. And the precision is not as good as you proposed. Your proposed top 1 acc is 73.97, however, what I got is only top 1 acc 67.25, top 5 acc 89.93. Could you please help me to solve the problem?
Thanks in advance!

**Comment by cecilia930426** [comment]
<img width="766" alt="WX20201019-165359@2x" src="https://user-images.githubusercontent.com/16661965/96510616-ca307880-122b-11eb-81d8-9194e3a8519d.png">
<img width="762" alt="WX20201019-165329@2x" src="https://user-images.githubusercontent.com/16661965/96510691-ea603780-122b-11eb-96e7-4bf47890ce57.png">

**Comment by zhaoyue-zephyrus** [comment]
Hi @cecilia930426 

 You may need to ask the MMAction2 team about this issue.

**Comment by cecilia930426** [comment]
Thanks!
