### ISSUE TITLE
temporal segment network load increases on inference

### ISSUE THREAD

**Issue by athulvingt** [open-mmlab/mmaction#219]
I tried inferencing on a pretrained TSN model for Action recognition from Gluon zoo. On inferencing the first few frames the CPU consumption was lower, but it gradually increased on inferencing on later frames

**Comment by yjxiong** [comment]
Hi @athulvingt are you referring to GluonCV model zoo? If so you can directly contact the GluonCV repo owner. This repo is MMAction, we don't quite know how to help with GluonCV issues.

**Comment by athulvingt** [comment]
I just wanted to know if TSN network stores previous data points (long term memory) like a RNN network

**Comment by yjxiong** [comment]
1. RNN in inference only stores the previous timestep's state.
2. TSN is a training framework. In inference the trained models work in per-frame  or per-snippet manner. 
3. Please consult the authors of the implementation you are using for performance issues.
