### ISSUE TITLE
error while making densflow, make: *** No targets specified and no makefile found.  Stop.

### ISSUE THREAD

**Issue by isalirezag** [open-mmlab/mmaction#22]
I see some steps got updated for densflow.
can you tell me how should i make densflow now.
it gives me the error
`make: *** No targets specified and no makefile found.  Stop.`
 when I do `make -j`

**Comment by isalirezag** [comment]
when i do this:
```
cd ../../dense_flow
mkdir build && cd build
OpenCV_DIR=../../opencv-4.1.0/build/  cmake ..
make -j
```
it shows 
```CMake Error: The source directory "/home/alireza/Desktop/MMAction/third_party/dense_flow" does not appear to contain CMakeLists.txt.```

**Comment by isalirezag** [comment]
should i download decoder from https://github.com/zhreshold/decord
or should decoder file has something in it by default? right now it is empty...

**Comment by zhaoyue-zephyrus** [comment]
@isalirezag  Did you clone **recursively**?

**Comment by isalirezag** [comment]
@zhaoyue-zephyrus yes, you mean like this?
git clone --recursive https://github.com/open-mmlab/mmaction.git

**Comment by zhaoyue-zephyrus** [comment]
@isalirezag yep, both the denseflow and decord are **submodules** of the project. Also please be careful with its version.
