### ISSUE TITLE
 can provide the flow data by baiduyun？

### ISSUE THREAD

**Issue by hushunda** [open-mmlab/mmaction#225]
Hope to be able to provide the UCF101  flow data by baiduyun？ @yjxiong

**Comment by Z-Xiong** [comment]
same question

**Comment by hushunda** [comment]
> same question
https://github.com/feichtenhofer/twostreamfusion

**Comment by Z-Xiong** [comment]
大佬，请问你有没有这个mmaction  TSN在UCF101上的预训练模型。官方的已经404了。这个：
https://open-mmlab.s3.ap-northeast-2.amazonaws.com/mmaction/models/ucf101/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth
