### ISSUE TITLE
Compile CUDA extension error

### ISSUE THREAD

**Issue by hyfalex** [open-mmlab/mmaction#26]
-DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=resample2d_cuda -D_GLIBCXX_USE_CXX11_ABI=0
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from resample2d_cuda.cc:2:0:
/home/alex/anaconda3/envs/mmaction/lib/python3.5/site-packages/torch/include/torch/csrc/api/include/torch/torch.h:7:2: warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
 #warning \

I have tried GCC 7.4, 5.5, 4.8. All of them does not work. 
My environment 
CUDA 10 (Although using nvcc -V it shows 9.1.85)
Pytorch 1.1 (Not from source, tried from source and still does not work)

**Comment by zhaoyue-zephyrus** [comment]
I think this is just a warning.. Just skipping it would be fine.

**Comment by yjxiong** [comment]
```
warning: #warning "Including torch/torch.h for C++ extensions is deprecated. Please include torch/extension.h" [-Wcpp]
#warning 
```

This is a deprecation warning. You can safely ignore it for now.
