### ISSUE TITLE
【test issue】No module named 'mmaction.models.tenons'

### ISSUE THREAD

**Issue by yyf8989** [open-mmlab/mmaction#27]
Failed to import ActivityNet evaluation toolbox. Did you clone with"--recursive"?
Failed to import ActivityNet evaluation toolbox. Did you clone with"--recursive"?
Traceback (most recent call last):
  File "tools/test_recognizer.py", line 10, in <module>
    from mmaction.models import build_recognizer, recognizers
  File "/home/yyf/.local/lib/python3.6/site-packages/mmaction-0.1rc0+f83b052-py3.6.egg/mmaction/models/__init__.py", line 1, in <module>
    from .tenons.backbones import *
ModuleNotFoundError: No module named 'mmaction.models.tenons'

who can help me solve this problem？tkx

**Comment by zhaoyue-zephyrus** [comment]
@yyf8989  You may need to add the path to mmaction to your `PYTHONPATH`.

Choose what you like most from the following choices:

1. Run the following in advance
```shell
export PYTHONPATH=`pwd`:$PYTHONPATH
```
2. Add the following line to your `~/.bashrc`
```shell
export PYTHONPATH=`/PATH/TO/YOUR/MMACTION/`:$PYTHONPATH
```
3. add it before every command so that it looks like:
```shell
PYTHONPATH=. python tools/test_recognizer.py ...
```

**Comment by yyf8989** [comment]
> @yyf8989 You may need to add the path to mmaction to your `PYTHONPATH`.
> 
> Choose what you like most from the following choices:
> 
> 1. Run the following in advance
> 
> ```shell
> export PYTHONPATH=`pwd`:$PYTHONPATH
> ```
> 
> 1. Add the following line to your `~/.bashrc`
> 
> ```shell
> export PYTHONPATH=`/PATH/TO/YOUR/MMACTION/`:$PYTHONPATH
> ```
> 
> 1. add it before every command so that it looks like:
> 
> ```shell
> PYTHONPATH=. python tools/test_recognizer.py ...
> ```
tks for your help！ I've solved the problem, but i met another problem below:
when i run command:
 PYTHONPATH=. python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py modelzoo/tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth --gpus 0
output:
ImportError: /home/yyf/code/mmaction/mmaction/ops/nms/nms_cuda.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3c105ErrorC1ENS_14SourceLocationERKSs

I found that this may be gcc-version's problem.  
can  you  help me ?  tkx~

**Comment by zhaoyue-zephyrus** [comment]
@yyf8989 Can you specify your environment such as GCC, CUDA, PyTorch. Actually I think this issue is related to pytorch. Check it out here: https://github.com/facebookresearch/maskrcnn-benchmark/issues/1

**Comment by yyf8989** [comment]
> @yyf8989 Can you specify your environment such as GCC, CUDA, PyTorch. Actually I think this issue is related to pytorch. Check it out here: [facebookresearch/maskrcnn-benchmark#1](https://github.com/facebookresearch/maskrcnn-benchmark/issues/1)

@zhaoyue-zephyrus 
here is my envs:
GCC 7.4.0
CUDA 10.0
Pytorch 1.0.1

I'm trying to create a new  conda env. for mmaction. 
I'll put it out if i solve this issue.

**Comment by yyf8989** [comment]
> @yyf8989 Can you specify your environment such as GCC, CUDA, PyTorch. Actually I think this issue is related to pytorch. Check it out here: [facebookresearch/maskrcnn-benchmark#1](https://github.com/facebookresearch/maskrcnn-benchmark/issues/1)

@zhaoyue-zephyrus 
here is my envs:
Python：3.6.8
GCC 7.4.0
CUDA 10.0
Pytorch 1.0.1

I'm trying to create a new  conda env. for mmaction. 
I'll put it out if i solve this issue.

**Comment by lmiles247** [comment]
Hi @yyf8989 ! Has this issue been resolved? I am running into the same problem. Thank you so much!
