### ISSUE TITLE
use dense_flow  to extract  frames error

### ISSUE THREAD

**Issue by yangyuke001** [open-mmlab/mmaction#28]
After installed  Decord and dense_flow successful,
I ran the script:extract_frames.sh,and I got the errors ,some of the  logs blew:

................
../third_party/dense_flow/build/extract_gpu: error while loading shared libraries: libcublas.so.9.1: cannot open shared object file: No such file or directory
...............

my device:
ubuntu-16.04
cuda-10.1
OpenCV 4.1.0
I download NVIDIA VIDEO CODEC SDK and copy the header files to my cuda path also.

Any help is appreciated！

**Comment by zhaoyue-zephyrus** [comment]
Are you building dense_flow with CUDA 9.1? Double check if both opencv and dense_flow is built with the same CUDA. If the error still occurs, add your path of `libcublas.so.9.1:` to `LD_LIBRARY_PATH` explicitly.

**Comment by yangyuke001** [comment]
@zhaoyue-zephyrus 
I give it up .
Thank you anyway.

**Comment by HuZia777** [comment]
1117 GolfSwing/v_GolfSwing_g11_c03 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1246 HorseRiding/v_HorseRiding_g07_c04 done
1283 HorseRiding/v_HorseRiding_g13_c01 done
1201 HorseRiding/v_HorseRiding_g01_c01 done
1328 HorseRiding/v_HorseRiding_g20_c04 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1284 HorseRiding/v_HorseRiding_g13_c02 done
1202 HorseRiding/v_HorseRiding_g01_c02 done
1329 HorseRiding/v_HorseRiding_g20_c05 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not foundtmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found

1285 HorseRiding/v_HorseRiding_g13_c03 done
1203 HorseRiding/v_HorseRiding_g01_c03 done
1330 HorseRiding/v_HorseRiding_g20_c06 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1286 HorseRiding/v_HorseRiding_g13_c04 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1331 HorseRiding/v_HorseRiding_g20_c07 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found1287 HorseRiding/v_HorseRiding_g14_c01 done

1332 HorseRiding/v_HorseRiding_g21_c01 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1288 HorseRiding/v_HorseRiding_g14_c02 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1289 HorseRiding/v_HorseRiding_g14_c03 done


can you help me?
