### ISSUE TITLE
Video download script 

### ISSUE THREAD

**Issue by bryanyzhu** [open-mmlab/mmaction#33]
Hi, I used the `https://github.com/open-mmlab/mmaction/blob/master/data_tools/kinetics400/download_videos.sh` script to download Kinetics dataset. However, I encountered the following error: 

```
line 19: [: too many arguments
line 27: [: too many arguments
```

Actually the videos are all downloaded ok. It is just the classes in the folder still have white spaces. It seems this line `if [ $class != $newclass ]` is not working correctly. I don't know if this is just me, or anyone also having this issue? Thank you.

**Comment by zhaoyue-zephyrus** [comment]
Hi @bryanyzhu 

Sorry I didn't check them well. Now you can refer to the new `https://github.com/open-mmlab/mmaction/blob/master/data_tools/kinetics400/rename_classnames.sh` to do so.
In a nutshell, the `$class` has to be quoted due to space and parentheses. Let me know if there is other issue.

**Comment by bryanyzhu** [comment]
@zhaoyue-zephyrus Thank you. I will close the issue.
