### ISSUE TITLE
Extremely slow training on Kinetics400 using video dataloader

### ISSUE THREAD

**Issue by bryanyzhu** [open-mmlab/mmaction#41]
Hi, I have a problem on Kinetics action recognition training. Since I don't have enough storage space, I decide to go for video dataloader training. The command line I am using is:

```
./tools/dist_train_recognizer.sh configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2_video.py 8 --validate
```

There is no error, but the training is extremely slow. Like below, it needs 132 days to finish training. 

```
2019-07-05 18:28:14,206 - INFO - workflow: [('train', 1)], max: 100 epochs
2019-07-05 18:38:44,201 - INFO - Epoch [1][20/3637]     lr: 0.01000, eta: 132 days, 14:08:21, time: 31.499, data_time: 11.109, memory: 5219, loss_cls: 6.0129, loss: 6.0129
```

I think I installed everything, I don't know why this happens. My suspicious is on video dataloader or some setting issues. Do you have any suggestions/ideas how to fix this? Thank you very much.

**Comment by zhaoyue-zephyrus** [comment]
Hi @bryanyzhu 

I suppose you did nothing to the config right? Then the problem is that the config uses a slow VideoReader by default. Changing https://github.com/open-mmlab/mmaction/blob/master/configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2_video.py#L42 to `use_decord=True` and you will experience a significant speedup. In my (not so strict) experiment, the speed is comparable to reading from frames. Also remember to update because I did some modification to the `VideoDataset`.

**Comment by bryanyzhu** [comment]
@zhaoyue-zephyrus Hi, thank you very much for your kind reply. I updated the codebase and set `use_decord=True`. But now I have the following error:

```
2019-07-09 00:03:45,847 - INFO - workflow: [('train', 1)], max: 100 epochs
[00:03:53] /home/ubuntu/yizhu/code/mmaction/third_party/decord/src/video/video_reader.cc:145: Video Reader width: 408 is not aligned with CPU alignment 
preference, causing non-compact array with degraded performance. Automatically round up resolution to: 416 x 367
[00:03:53] /home/ubuntu/yizhu/code/mmaction/third_party/decord/src/video/video_reader.cc:145: Video Reader width: 270 is not aligned with CPU alignment 
preference, causing non-compact array with degraded performance. Automatically round up resolution to: 272 x 362
terminate called after throwing an instance of 'dmlc::Error'
  what():  [00:03:53] /home/ubuntu/yizhu/code/mmaction/third_party/decord/src/video/ffmpeg/ffmpeg_common.h:192: Check failed: p->linesize[0] % p->width 
== 0 AVFrame data is not a compact array. linesize: 864 width: 272
```

I'm trying to figure out why, but if you have suggestions, please let me know. Thank you.

**Comment by tea1528** [comment]
You may refer to issue #12 for more detail. In short, you might want to resize your videos to some fixed resolution. If not, Deocrd will throw series of errors. 

Decord still seems to have problems like [random access in later frames](https://github.com/zhreshold/decord/issues/2).

You may want to use Decord with some caution.

**Comment by bryanyzhu** [comment]
@tea1528 Thank you for letting me know these two related issues, they help a lot. I will try fixed resolution video first.
