### ISSUE TITLE
No module named 'traj_conv_cuda'

### ISSUE THREAD

**Issue by dagongji10** [open-mmlab/mmaction#43]
when I prepare to test the inference, I got this error
![image](https://user-images.githubusercontent.com/15357846/60854935-7b2c2300-a234-11e9-807b-fd2e36deac26.png)
I checked all the Requirements except decord and dense_flow. I saw thay are optional then did not build these two.
Could you tell me why this happen? How to solve this? 
Thank you!

**Comment by zhaoyue-zephyrus** [comment]
Hi @dagongji10  

This might be that you didn't install the c++/cuda extensions well. Run `bash compile.sh` and see if there is any error. Also as a workaround, you can also simply comment this line `from ....ops.trajectory_conv_package.traj_conv import TrajConv`.

**Comment by dagongji10** [comment]
@zhaoyue-zephyrus I have run the file compile.sh, but there are 2 errors when build resample2d and trajectory_conv just like this
![image](https://user-images.githubusercontent.com/15357846/60950515-e572bf80-a329-11e9-8ed3-d32684a156ec.png)
It seems that the PYTHONPATH is wrong. Maybe I need to change the setup of my python-path for mmaction. But how to do that?
 I build mmaction in my python virtualenv environment, and the system is “CentOS Linux release 7.4.1708”.

**Comment by zhaoyue-zephyrus** [comment]
@dagongji10  Sorry I don't have much experience in virtualenv. Actually you can create and manage environment using anaconda or miniconda (https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html). If you would stick to virtualenv, maybe you can try adding PYTHONPATH by writing `export PYTHONPATH=$PYTHONPATH:/home/cock/.local/lib/python3.5/site-packages/` in your `~/.bashrc`?

**Comment by dagongji10** [comment]
@zhaoyue-zephyrus so much thanks for your help. I add PYTHONPATH by writing export PYTHONPATH=$PYTHONPATH:/root/.local/lib/python3.5/site-packages/ in ~/.bashrc, and the error above seems gone. Now I need to solve the next error:
![image](https://user-images.githubusercontent.com/15357846/61192604-2e3ec580-a6e8-11e9-95c5-7b71c99dbd4a.png)
That's because I didn't get the UCF101, maybe I can try to solve it by myself. If I cann't do that, I will back.

Thanks very much.

**Comment by dagongji10** [comment]
@zhaoyue-zephyrus Hello, I'm back. I have several question this time:

1. I run the test_recognizer.py file, but get OOM error
![image](https://user-images.githubusercontent.com/15357846/61284131-f1122a80-a7f0-11e9-94f0-ac90b8a083c8.png)
I want to know that how much memory it will take? Can I use less test images to make it run smoothly?

2. I check the num of test dataset, it show 3783. But ucf101_val_split_1_rawframes.txt only have 3725 lines? What's the problem?
![image](https://user-images.githubusercontent.com/15357846/61284485-a04f0180-a7f1-11e9-9329-c305f4cc0cf7.png)
![image](https://user-images.githubusercontent.com/15357846/61284593-d8eedb00-a7f1-11e9-8b9c-28716669b6a2.png)

3. In your paper chapter4.2, when deal with untrimmed videos, sliding-windows use top-k pooling and then averaged for the final result, does it mean one action for one video? Can I know start-end time of the result action? And if there are more than one action in a frame, can TSN know that?
I have not run the test_detector.py/test_localizer.py, the question may seem stupid, but I cann't wait to know that.

Thanks!

**Comment by dagongji10** [comment]
@zhaoyue-zephyrus It's realy really appreciate your help. I change the `num_segments` to 10, it works well. Finnally, I can get the test result.
![image](https://user-images.githubusercontent.com/15357846/61445865-c5be4580-a980-11e9-8969-8dde6ecf54d4.png)
Next I will try to read and understand your code, the code is beautiful.

The paper is 《Temporal Segment Networks for Action Recognition in Videos》2017, in fact I have began study SSN now. You guys realy do a nice work!

Thank you so much.

**Comment by zhaoyue-zephyrus** [comment]
@dagongji10 

I see. Action recognition in untrimmed videos (sec 4.2 in that PAMI paper) assumes that one (or very few, e.g. two) action in a single video indeed. As of the SSN, I hope I can finish the full functionalities of SSN in MMAction soon. Thanks for your interests in our works!

**Comment by duanyao** [comment]
This issue also happens to venv. In a virtual env, one should not install packages to the user global site (`~/.local/lib/pythonX.Y/site-packages/` ), because doing so breaks encapsule of virtual env. So `--user` option of pip and setuptools should never be used in a virtual env. See also https://github.com/pypa/pip/issues/5702 .

So the fix is not setting `PYTHONPATH`, but removing `--user` option in `compile.sh`.
