### ISSUE TITLE
Training & Testing a recognizer on a different dataset (NTU rgb)

### ISSUE THREAD

**Issue by sparsh-b** [open-mmlab/mmaction#45]
Hi @zhaoyue-zephyrus !

I am trying to train & test the TSN model on NTU dataset. I am following the instructions given in dataset.md file. Say I'm able to extract frames & generated the filelist, what should I have to do further? Should I modify any of the scripts? Also, how should I prepare config files for NTU? (Can seeing the config for UCF101 & preparing a similar one for NTU suffice?)

**Comment by sparsh-b** [comment]
Dear @zhaoyue-zephyrus ,

I am able to extract frames & build the fielist. Plz give me clues on how to go about preparing the config file for a different dataset.

**Comment by sparsh-b** [comment]
Hi @zhaoyue-zephyrus !
No problem. Is there any other place where i should change the `num_classes` 

Because, when i'm training, the following log occurs:

2019-07-19 16:27:34,866 - INFO - workflow: [('train', 1)], max: 80 epochs
_/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [5,0,0] **Assertion `t >= 0 && t < n_classes` failed.**
/pytorch/aten/src/THCUNN/ClassNLLCriterion.cu:105: void cunn_ClassNLLCriterion_updateOutput_kernel(Dtype *, Dtype *, Dtype *, long *, Dtype *, int, int, int, int, long) [with Dtype = float, Acctype = float]: block: [0,0,0], thread: [6,0,0] **Assertion `t >= 0 && t < n_classes` failed.**_
Traceback (most recent call last):
  File "./tools/train_recognizer.py", line 90, in <module>
    main()
  File "./tools/train_recognizer.py", line 86, in main
    logger=logger)
  File "/media/HDD_2TB/sparsh/mmaction-master/mmaction/apis/train.py", line 57, in train_network
    _dist_train(model, dataset, cfg, validate=validate)
  File "/media/HDD_2TB/sparsh/mmaction-master/mmaction/apis/train.py", line 102, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_epochs)
  File "/home/sparsh/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 358, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/home/sparsh/.local/lib/python3.6/site-packages/mmcv/runner/runner.py", line 264, in train
    self.model, data_batch, train_mode=True, **kwargs)
  File "/media/HDD_2TB/sparsh/mmaction-master/mmaction/apis/train.py", line 37, in batch_processor
    loss, log_vars = parse_losses(losses)
  File "/media/HDD_2TB/sparsh/mmaction-master/mmaction/apis/train.py", line 30, in parse_losses
    log_vars[name] = log_vars[name].item()
_RuntimeError: CUDA error: device-side **assert** triggered_
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side **assert** triggered (insert_events at /pytorch/c10/cuda/CUDACachingAllocator.cpp:564)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fe16d601441 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fe16d600d7a in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x13652 (0x7fe16b67f652 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libc10_cuda.so)
frame #3: c10::TensorImpl::release_resources() + 0x50 (0x7fe16d5f1ce0 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #4: <unknown function> + 0x30facb (0x7fe16c01bacb in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x3798a3 (0x7fe16c0858a3 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #6: torch::autograd::deleteFunction(torch::autograd::Function*) + 0xcd (0x7fe16c01e9cd in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release() + 0xa2 (0x7fe177f13bb2 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #8: <unknown function> + 0x14216b (0x7fe177f3716b in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: <unknown function> + 0x1421d9 (0x7fe177f371d9 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #10: torch::autograd::Variable::Impl::release_resources() + 0x1b (0x7fe16c65808b in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #11: <unknown function> + 0x1420bb (0x7fe177f370bb in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #12: <unknown function> + 0x3c30f4 (0x7fe1781b80f4 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #13: <unknown function> + 0x3c3141 (0x7fe1781b8141 in /home/sparsh/.local/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #14: <unknown function> + 0x1993cf (0x55bf7fe5e3cf in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #15: <unknown function> + 0xf18e8 (0x55bf7fdb68e8 in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #16: <unknown function> + 0xf12b7 (0x55bf7fdb62b7 in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #17: <unknown function> + 0xf1147 (0x55bf7fdb6147 in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #18: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #19: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #20: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #21: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #22: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #23: <unknown function> + 0xf115d (0x55bf7fdb615d in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #24: PyDict_SetItem + 0x3da (0x55bf7fdfbe7a in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #25: PyDict_SetItemString + 0x4f (0x55bf7fe0478f in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #26: PyImport_Cleanup + 0x99 (0x55bf7fe68709 in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #27: Py_FinalizeEx + 0x61 (0x55bf7fed45f1 in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #28: Py_Main + 0x35e (0x55bf7fedf1fe in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #29: main + 0xee (0x55bf7fda802e in /home/sparsh/anaconda3/envs/venv/bin/python)
frame #30: __libc_start_main + 0xe7 (0x7fe17ca01b97 in /lib/x86_64-linux-gnu/libc.so.6)
frame #31: <unknown function> + 0x1c3e0e (0x55bf7fe88e0e in /home/sparsh/anaconda3/envs/venv/bin/python)

After this log, nothing happens & the cursor is just bllinking. So, i had to do ctrl+C.

Thanks for your help!

**Comment by zhaoyue-zephyrus** [comment]
@sparsh-b 

Take a look at your filelist. Ensure that every `label` (the 3rd element of each row) should be less than the `num_classes`. Also please quote your error log next to avoid issue reference.

**Comment by sparsh-b** [comment]
Thanks! This error is solved as of now. Previously my class labels were from 1..60. Now, I changed it from 0..59. I've started training with 2 GPUs & ETA is 1 day.

Sorry for that issue referencing mishap. Didn't see that coming. I edited the previous comment.

**Comment by sparsh-b** [comment]
@zhaoyue-zephyrus 
I am trying to continue training the model from the point where it stopped. To do this i did the following:

1) gave the path to the symlink (`work_dirs/tsn_2d_rgb_bninception_seg_3_f1s1_b32_g8/latest.pth`) via the `--resume_from` argument to https://github.com/open-mmlab/mmaction/blob/760c78cf440a42dc6ec72410e9a8b95acab1c85f/tools/dist_train_recognizer.sh#L5 
2) gave the same symlink path in https://github.com/open-mmlab/mmaction/blob/760c78cf440a42dc6ec72410e9a8b95acab1c85f/configs/ucf101/tsn_rgb_bninception.py#L125 

Plz let me know if there is anything else that i need to do to resume training. Thanks!

**Comment by zhaoyue-zephyrus** [comment]
@sparsh-b Sorry about the late reply. Your option (2) should work. Is it working properly?

**Comment by sparsh-b** [comment]
Yeah, it worked. Thanks!

**Comment by chenyihang1993** [comment]
@sparsh-b Hi, I'd like to know the accuray on NTU rgb using TSN network. Could you please tell me the accuracy? Looking forward to your reply! THX!

**Comment by JaiDoshi** [comment]
Can you please tell the accuracy you obtained on NTU RGB?
