### ISSUE TITLE
about the TSN3D 

### ISSUE THREAD

**Issue by Usernamezhx** [open-mmlab/mmaction#46]
First. thanks for your great work. I can run the TSN2D successfully. I want to run the TSN3D to compare to 2D. Can you supply the 3D model config. or it is same as the 2D config ? can you supply the paper about the difference between them. thanks advance.

**Comment by Usernamezhx** [comment]
when I use the date loader for the TSN3D . I get the input size is [32, 3, 3, 224, 224]. and then reshape it to [93, 3, 224, 224]. next you use the img_forward = img_group[:, :, 1:, :, :] to process the date. but the index is out of the range.Can you supply detail about the TSN3D config ? thanks in advance.

**Comment by zhaoyue-zephyrus** [comment]
@Usernamezhx  To run the TSN3D, you can refer to https://github.com/open-mmlab/mmaction/blob/master/configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py.  This I3D model can be seen as a simplified version of TSN3D with a *single* segment.
Changing the `num_segments` in https://github.com/open-mmlab/mmaction/blob/master/configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py#L53 & https://github.com/open-mmlab/mmaction/blob/master/configs/kinetics400/i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py#L77 to the number you wish. Check if it works.

**Comment by Usernamezhx** [comment]
@zhaoyue-zephyrus  yeah. it can work. thank you very much.

**Comment by lmiles247** [comment]
Hello @zhaoyue-zephyrus ! Thank you so much for providing this solution. 

I apologize, but I am slightly confused. Does this implementation of TSN3D only take in the RGB modality? Or does this feed in both RGB and optical flows? I see in the model dict that we include the spatial_temporal_module, but I can't seem to find where we actually pull in the optical flow images in the code. 

If this does not consider both RGB and TVL1 Optical Flows, then do you have a suggestion for how to do this?

Thank you so much for your help!!
