### ISSUE TITLE
How can I modify the codes to get action recognition result for a single video ?

### ISSUE THREAD

**Issue by Viarow** [open-mmlab/mmaction#48]
To start with, thanks for your excellent works, it really brings a lot of convenience.
Here I would like to modify the codes to get the classification/recognition results for a single video using TSN and I3D.  Since the repository is quite large, I am not sure about the exact steps to do though having some vague clues.

Specifically, can I make a dataset containing just one or a few videos  and arrange it with the same structure of UCF101 so that I can also use your codes to extract frames and pre-process the  video data?
Where should I add or modify the codes to present the classification results for a video (our testing video categories will be the same as those in UCF101)? I guess test_recognizer.py maybe?
And what changes do I need to make to config files? 

Could you please give me some instructions to do the modifications?
By the way, Does it mean I need to install Decord and dense-flow both to realize my modifications?

Thank you so much !

**Comment by zhaoyue-zephyrus** [comment]
@Viarow  We are planning to add this feature (predicting a single video) in the near future. For the time being, sorry but you have to hack a little bit.

To prepare the data, you can refer to https://github.com/open-mmlab/mmaction/blob/master/DATASET.md#extract-frames for some explanation and modify the scripts `data_tools/ucf101/`. 
Then you can use `tools/test_recognizer.py` to get the output scores. The things you have to change are: (1) Replace the `ann_file` in https://github.com/open-mmlab/mmaction/blob/master/configs/ucf101/tsn_rgb_bninception.py#L82 with your own video file list. (2) Specify  `--out results.pkl` (https://github.com/open-mmlab/mmaction/blob/master/tools/test_recognizer.py#L47) to dump the classification scores in a .pkl file.

**Comment by Viarow** [comment]
Thank you for the instructions, I will try to tackle the details myself.

**Comment by zhaoyue-zephyrus** [comment]
@Viarow 

Good. Feel free to comment below this issue if there is any other problem.
