### ISSUE TITLE
issues while building opencv-4.1.0 while dense_flow installation

### ISSUE THREAD

**Issue by sparsh-b** [open-mmlab/mmaction#50]
The following is the log when i ran the command:
`cmake -DCMAKE_BUILD_TYPE=Release -DWITH_CUDA=ON -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib-4.1.0/modules/ -DWITH_TBB=ON -DBUILD_opencv_cnn_3dobj=OFF -DBUILD_opencv_dnn=OFF -DBUILD_opencv_dnn_modern=OFF -DBUILD_opencv_dnns_easily_fooled=OFF ..`

**Please let me know if there is any problem in general & particularly at the bolded lines...**

-- Looking for ccache - found (/home/sparsh/anaconda3/envs/venv/bin/ccache)
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found suitable version "1.2.11", minimum required is "1.2.3")
**-- Could NOT find Jasper (missing: JASPER_LIBRARIES JASPER_INCLUDE_DIR) (tried sudo apt-get install jasper. but didnt fix the problem)**
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11")
-- Found OpenEXR: /usr/lib/x86_64-linux-gnu/libIlmImf.so
-- Found TBB (env): /usr/lib/x86_64-linux-gnu/libtbb.so
-- found Intel IPP (ICV version): 2019.0.0 [2019.0.0 Gold]
-- at: /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/3rdparty/ippicv/ippicv_lnx/icv
-- found Intel IPP Integration Wrappers sources: 2019.0.0
-- at: /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/3rdparty/ippicv/ippicv_lnx/iw
-- CUDA detected: 9.1
-- CUDA NVCC target flags: -gencode;arch=compute_30,code=sm_30;-gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-D_FORCE_INLINES
-- LAPACK(Atlas): LAPACK_LIBRARIES: /usr/lib/x86_64-linux-gnu/liblapack.so;/usr/lib/x86_64-linux-gnu/libcblas.so;/usr/lib/x86_64-linux-gnu/libatlas.so
-- LAPACK(Atlas): Support is enabled.
**-- VTK support is disabled. Compilation of the sample code has failed. (Installed vtk module in the virtual env i'm using in anaconda. But, still the problem persists)**
-- OpenCV Python: during development append to PYTHONPATH: /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/python_loader
**-- Caffe:   NO
-- Protobuf:   NO (should these be worried about?)**
-- Glog:   YES
-- freetype2:   YES
-- harfbuzz:    YES
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
**-- Module opencv_ovis disabled because OGRE3D was not found (No help by googling the error)**
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /home/sparsh/anaconda3/envs/venv/lib/cmake/gflags
-- Detected gflags version: 2.2.2
CMake Warning at /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/CMakeFiles/CMakeTmp/CMakeLists.txt:17 (add_executable):
  Cannot generate a safe runtime search path for target cmTC_e8fd2 because
  files in some directories may conflict with libraries in implicit
  directories:

runtime library [libglog.so.0] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
      /home/sparsh/anaconda3/envs/venv/lib

Some of these libraries may not be found correctly.

-- Checking SFM deps... TRUE
-- Module opencv_sfm disabled because the following dependencies are not found: Eigen
-- Module opencv_dnn_objdetect disabled because opencv_dnn dependency can't be resolved!
-- Module opencv_text disabled because opencv_dnn dependency can't be resolved!
-- HDF5: Using hdf5 compiler wrapper to determine C configuration
-- freetype2:   YES
-- harfbuzz:    YES

-- General configuration for OpenCV 4.1.0 =====================================
--   Version control:               unknown

--   Extra modules:
--     Location (extra):            /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv_contrib-4.1.0/modules
--     Version control (extra):     unknown

--   Platform:
--     Timestamp:                   2019-07-16T15:06:58Z
--     Host:                        Linux 4.18.0-25-generic x86_64
--     CMake:                       3.10.2
--     CMake generator:             Unix Makefiles
--     CMake build tool:            /usr/bin/make
--     Configuration:               Release

--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_1 (15 files):         + SSSE3 SSE4_1
--       SSE4_2 (2 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (1 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (28 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (1 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_SKX

--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ Compiler:                /usr/bin/c++  (ver 7.4.0)
--     C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
--     C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Winit-self -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
--     C Compiler:                  /usr/bin/cc
--     C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
--     C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Winit-self -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
--     Linker flags (Release):      -Wl,--gc-sections
--     Linker flags (Debug):        -Wl,--gc-sections
--     ccache:                      YES
--     Precompiled headers:         NO
--     Extra dependencies:          m pthread cudart_static -lpthread dl rt nppc nppial nppicc nppicom nppidei nppif nppig nppim nppist nppisu nppitc npps cublas cufft -L/usr/lib/x86_64-linux-gnu
--     3rdparty dependencies:

--   OpenCV modules:
--     To be built:                 aruco bgsegm bioinspired calib3d ccalib core cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev datasets dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc line_descriptor ml objdetect optflow phase_unwrapping photo plot quality reg rgbd saliency shape stereo stitching structured_light superres surface_matching tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    dnn world
--     Disabled by dependency:      dnn_objdetect text
--     Unavailable:                 cnn_3dobj cvv java js matlab ovis python2 python3 sfm viz
--     Applications:                tests perf_tests apps
--     Documentation:               NO
--     Non-free algorithms:         NO

--   GUI:
--     GTK+:                        YES (ver 3.22.30)
--       GThread :                  YES (ver 2.56.4)
**--       GtkGlExt:                  NO 
--     VTK support:                 NO (######Should these be worried about?######)**

--   Media I/O:
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
--     WEBP:                        /usr/lib/x86_64-linux-gnu/libwebp.so (ver encoder: 0x020e)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
--     JPEG 2000:                   build (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2.2.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES

--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (57.107.100)
--       avformat:                  YES (57.83.100)
--       avutil:                    YES (55.78.100)
--       swscale:                   YES (4.8.100)
--       avresample:                YES (3.7.0)
--     GStreamer:                   YES (1.14.4)
--     v4l/v4l2:                    YES (linux/videodev2.h)

--   Parallel framework:            TBB (ver 2017.0 interface 9107)

--   Trace:                         YES (with Intel ITT)

--   Other third-party libraries:
--     Intel IPP:                   2019.0.0 Gold [2019.0.0]
--            at:                   /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/3rdparty/ippicv/ippicv_lnx/icv
--     Intel IPP IW:                sources (2019.0.0)
--               at:                /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build/3rdparty/ippicv/ippicv_lnx/iw
--     Lapack:                      YES (/usr/lib/x86_64-linux-gnu/liblapack.so /usr/lib/x86_64-linux-gnu/libcblas.so /usr/lib/x86_64-linux-gnu/libatlas.so)
--     Eigen:                       NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)

--   NVIDIA CUDA:                   YES (ver 9.1, CUFFT CUBLAS NVCUVID)
--     NVIDIA GPU arch:             30 35 37 50 52 60 61 70
--     NVIDIA PTX archs:

--   OpenCL:                        YES (no extra features)
--     Include path:                /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load

--   Python (for build):            /usr/bin/python2.7

--   Java:
**--     ant:                         NO (######Should this be worried about?######)**
--     JNI:                         /home/sparsh/anaconda3/envs/venv/include /home/sparsh/anaconda3/envs/venv/include/linux /home/sparsh/anaconda3/envs/venv/include
**--     Java wrappers:               NO
--     Java tests:                  NO (######Should these be worried about?######)**

--   Install to:                    /usr/local
-- -----------------------------------------------------------------

-- Configuring done
-- Generating done
-- Build files have been written to: /media/HDD_2TB/sparsh/mmaction-master/third_party/opencv-4.1.0/build

**Comment by zhaoyue-zephyrus** [comment]
Hi @sparsh-b  sorry about the late reply. Do you have any problem when doing `make`?

**Comment by mikeyEcology** [comment]
I'm having trouble installing dense_flow and I have tried a number of options from the issues pages. I'm using cudatoolkit 11, so I don't know if this is the problem?
When I run `make -j` following the instructions at `INSTALL.md`, I get this error:

> [  7%] Building CXX object CMakeFiles/denseflow.dir/src/dense_flow_gpu.cpp.o
[ 14%] Building CXX object CMakeFiles/denseflow.dir/src/dense_warp_flow_gpu.cpp.o
/home/mtabak/repos/mmaction/third_party/dense_flow/src/dense_flow_gpu.cpp:6:10: fatal error: opencv2/cudaarithm.hpp: No such file or directory
    6 | #include "opencv2/cudaarithm.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~

Using:
Ubuntu 20.04
Cuda compilation tools, release 11.1, V11.1.74

Does anyone have ideas? Thank you in advance.
