### ISSUE TITLE
Error while using test_recognizer.py

### ISSUE THREAD

**Issue by marcosaurajn** [open-mmlab/mmaction#52]
I get this error in the prompt and I am not sure why, should I modify the dimensions? Or there are some data specifications missing:

**completed: 0, elapsed: 0sTraceback (most recent call last):
  File "tools/test_recognizer.py", line 122, in <module>
    main()
  File "tools/test_recognizer.py", line 112, in main
    outputs[0].shape[0]))
IndexError: list index out of range**

Thanks for the help.

**Comment by sparsh-b** [comment]
Hi @marcosaurajn !

It is possible that while extracting frames from videos, some videos didnt get extracted properly. What ur error possibly means is that some of the videos didn't output any frames at all & hence the lines corresponding to those videos in ur rawframes filelist (ucf101_val_split_1_rawframes.txt) are not in the format of: `$vid_id $num_frames $label`. i.e, `$num_frames` is missing. 

Maybe try to re-extract those particular videos.

I have faced a similar issue. Plz refer to issue #23

**Comment by zhaoyue-zephyrus** [comment]
@marcosaurajn , Sorry for the reply. @sparsh-b  has well explained and thank you for the explanation.
