### ISSUE TITLE
Decord Compile Error

### ISSUE THREAD

**Issue by PremiLabXJTLU** [open-mmlab/mmaction#6]
![11](https://user-images.githubusercontent.com/5770819/60031718-d1974e80-96d7-11e9-8db3-ed23a460138d.jpg)
![22](https://user-images.githubusercontent.com/5770819/60031834-01deed00-96d8-11e9-9e3f-a42fe2af901a.jpg)

I followed the exact step of install.md, but error occurs when I do the "make" operation

**Comment by zhaoyue-zephyrus** [comment]
Hi @banzhuan37 ,

Which version of FFmpeg are you using?

To check, please use command `ffmpeg -version`.

**Comment by kennymckormick** [comment]
You can use 'pip install decord' to install decord now, which doesn't require compiling.
