### ISSUE TITLE
SSN train and test error

### ISSUE THREAD

**Issue by smilefish06** [open-mmlab/mmaction#63]
When I try to train/test the SSN, I met the same error:

 File "/data/mmaction/mmaction/models/tenons/spatial_temporal_modules/simple_spatial_module.py", line 23, in forward
    return self.op(input)
  File "/.local/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/.local/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 563, in forward
    self.padding, self.ceil_mode, self.count_include_pad)
RuntimeError: Given input size: (1024x6x7). Calculated output size: (1024x0x1). Output size is too small at /pytorch/aten/src/THCUNN/generic/SpatialAveragePooling.cu:47

It seems the error came from the average pooling, the output size is too small (1024x0x1). Who can help on this? I use two GPUs.

**Comment by zhaoyue-zephyrus** [comment]
Hi @smilefish06 , the problem arises probably the extracted THUMOS14 frames are 320x180 by default. The `keep_resize_ratio` is `True` by default but fails to produce enough height. Please consider changing `keep_resize_ratio` in https://github.com/open-mmlab/mmaction/blob/master/configs/thumos14/ssn_thumos14_rgb_bn_inception.py#L87 to `False` to see if it works. Sorry about the inconvenience!

**Comment by smilefish06** [comment]
Yes, it works. Thanks!
