### ISSUE TITLE
Dense flow: extract_gpu not found

### ISSUE THREAD

**Issue by jakeandersenl** [open-mmlab/mmaction#68]
Good morning, I'm having trouble extracting the frames  with the example ucf101.
I have been reading other issues but I just can solve the problem. I'm quit sure I have install denseflow and openCV with the same CUDA, my CUDA version is 9.2.
Thank you in advance for your help.
![Screenshot from 2019-08-05 10-47-47](https://user-images.githubusercontent.com/53747245/62451436-93795a00-b76e-11e9-8b3e-9a0e90086b7a.png)

**Comment by zhaoyue-zephyrus** [comment]
@jakeandersenl  Do you have any installation log available? By the way, please first check the path to ensure that `extract_gpu` is generated.

**Comment by jakeandersenl** [comment]
Yes extract GPU is to be found in that directory ( attached pic), this is the info generated in the log:
[
[myeasylog.log](https://github.com/open-mmlab/mmaction/files/3487022/myeasylog.log)
![build_folder](https://user-images.githubusercontent.com/53747245/62791240-06673580-bacd-11e9-9fab-39a4d183c52e.png)

](url)

**Comment by mynameismaxz** [comment]
could you check ```path``` in a script. I found this problem too and just fixed by fixed full path of ```extract_gpu```.

**Comment by jakeandersenl** [comment]
Could you explain how you fixed it more in detail? I have checked some paths  but I'm not sure I'm looking for it in the correct location. Thanks in advance.

**Comment by mynameismaxz** [comment]
> Could you explain how you fixed it more in detail? I have checked some paths but I'm not sure I'm looking for it in the correct location. Thanks in advance.

Are you using ```ucf101``` right? For the first, you could extract frame by using file ```extract_frame.sh```. In this file, you could see bash to execute python file called ```build_rawframes.py```. You could fix the path in this file on function ```parse_args(): ```.

So you could found a path of dense_flow inline 98 (https://github.com/open-mmlab/mmaction/blob/master/data_tools/build_rawframes.py#L98). you could change that into the full path of check the correct path of dense_flow that you complied.

**Comment by jakeandersenl** [comment]
Thank you! I was able to fix it with your instructions. A wrong path  in `build_rawframes.py` , sorry for the late response, I've been bussy this month.

**Comment by HuZia777** [comment]
###I have this problem,but I can not find extract.gpu,how can I solve it?

1117 GolfSwing/v_GolfSwing_g11_c03 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1246 HorseRiding/v_HorseRiding_g07_c04 done
1283 HorseRiding/v_HorseRiding_g13_c01 done
1201 HorseRiding/v_HorseRiding_g01_c01 done
1328 HorseRiding/v_HorseRiding_g20_c04 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1284 HorseRiding/v_HorseRiding_g13_c02 done
1202 HorseRiding/v_HorseRiding_g01_c02 done
1329 HorseRiding/v_HorseRiding_g20_c05 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not foundtmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found

1285 HorseRiding/v_HorseRiding_g13_c03 done
1203 HorseRiding/v_HorseRiding_g01_c03 done
1330 HorseRiding/v_HorseRiding_g20_c06 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1286 HorseRiding/v_HorseRiding_g13_c04 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1331 HorseRiding/v_HorseRiding_g20_c07 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found1287 HorseRiding/v_HorseRiding_g14_c01 done

1332 HorseRiding/v_HorseRiding_g21_c01 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1288 HorseRiding/v_HorseRiding_g14_c02 done
sh: 1: tmp/yu/mmaction/third_party/dense_flow/build/extract_gpu: not found
1289 HorseRiding/v_HorseRiding_g14_c03 done

**Comment by HuZia777** [comment]
@MarcosJNS  could you share the code about /third_party/dense_flow/build to 331183622@qq.com?thank you
I found there has no file in the dense_flow ,thank you
