### ISSUE TITLE
Support for ActivityNet?

### ISSUE THREAD

**Issue by Frostinassiky** [open-mmlab/mmaction#69]
Dear Authors,

Thanks for your work in the community. This toolbox is very well-developed and useful!

Are you still working on the project? When do you plan to publish the code to support ActivityNet1.3?

**Comment by zhaoyue-zephyrus** [comment]
Hi @Frostinassiky  The project is still under development. Since I have to do research as well, I cannot guarantee the exact time schedule for ActivityNet 1.3 but it will be supported according to the roadmap (#1) we announced.

**Comment by Frostinassiky** [comment]
OK. Thanks for your reply. Good luck with your research!
