### ISSUE TITLE
dense_flow Compile Error

### ISSUE THREAD

**Issue by banzhuan37** [open-mmlab/mmaction#7]
![33](https://user-images.githubusercontent.com/5770819/60032098-787bea80-96d8-11e9-9362-4102956578dc.png)
![44](https://user-images.githubusercontent.com/5770819/60032232-b8db6880-96d8-11e9-91db-790c07b9848a.png)

error occurred at cmake step

**Comment by huiyang865** [comment]
I also meet this issue, while compiling to install opencv2.4:

-- Looking for linux/videodev.h
-- Looking for linux/videodev.h - not found
-- Looking for linux/videodev2.h
-- Looking for linux/videodev2.h - found
-- Looking for sys/videoio.h
-- Looking for sys/videoio.h - not found
-- checking for module 'libavcodec'
--   found libavcodec, version 58.35.100
-- checking for module 'libavformat'
--   found libavformat, version 58.20.100
-- checking for module 'libavutil'
--   found libavutil, version 56.22.100
-- checking for module 'libswscale'
--   found libswscale, version 5.3.100
-- checking for module 'libavresample'
--   package 'libavresample' not found
-- Looking for libavformat/avformat.h
-- Looking for libavformat/avformat.h - found
-- Looking for ffmpeg/avformat.h
-- Looking for ffmpeg/avformat.h - not found

Some files not exist in Ubuntu system.

**Comment by zhaoyue-zephyrus** [comment]
@banzhuan37 @huiyang865 : Please show your full error log. The current snapshot doesn't provide any useful information. Also please specify your environment, like other issues do.

**Comment by huiyang865** [comment]
This issue is from opencv-2.4 installation.

When I install the opencv-4.1 release, everything is OK. 

Suggest to close this issue. @banzhuan37

**Comment by yjxiong** [comment]
Closing this. Please feel free to reopen it if you meet any further problem.
