### ISSUE TITLE
About the backbone for I3D in configs/kinetics400/

### ISSUE THREAD

**Issue by Viarow** [open-mmlab/mmaction#71]
To start with, thank you so much for the instructions on testing the pre-trained TSN model, I can successfully get the precise result for any video and do some tweaking with your code.

When I look into the configs file for I3D under the directory /configs/kinetics, I found the backbone chosen for both configuration files is 'ResNet_I3D', while I also find a backbone named 'InceptionV1_I3D'.  

If I want to test with the original I3D network described in Deepmind's paper  , which config file should I use? Can I simply change the backbone 'type' and 'pretrained' attributes in the code?
Specifically, 'type' changed to 'InceptionV1_I3D' & 'pretrained' changed to 'open-mmlab://bninception_caffe' ? 

Thank you in advance!

**Comment by Viarow** [comment]
By the way, after doing `bash download_annotations.sh` I found that the files are already removed from deepmind's website.
Is the road_map.txt at https://github.com/deepmind/kinetics-i3d/blob/master/data/label_map.txt an alternative for classInd.txt ？ And there should also be kinetics_val.csv and kinetics_train.csv, which I found in the ActivityNet crawler.

**Comment by innerlee** [comment]
FYI This fork fixed the download https://github.com/innerlee/mmaction/tree/zz/fmt

**Comment by Viarow** [comment]
Thank you for your fixation, I have already solved the data set downloading problem thanks to the ActivityNet crawler, as for the original i3d network, I turned to the official repository released by Deepmind, anyway I still hope the authors of mmaction could add the pretrained model corresponding to the 'InceptionV1_I3D'  backbone.

**Comment by zhaoyue-zephyrus** [comment]
Hi @Viarow 

The official model in InceptionV1-I3D from DeepMind has been made available in the latest PR (https://github.com/open-mmlab/mmaction/pull/142). Hope that it is not that late. :)
