### ISSUE TITLE
unexpected key in source state_dict: fc.weight, fc.bias

### ISSUE THREAD

**Issue by jiangzhubo** [open-mmlab/mmaction#75]
Hi, I am running command:
python tools/test_recognizer.py configs/ucf101/tsn_rgb_bninception.py tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth --gpus 8

and i got follow error:
The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

Traceback (most recent call last):
  File "tools/test_recognizer.py", line 122, in <module>
    main()
  File "tools/test_recognizer.py", line 73, in main
    load_checkpoint(model, args.checkpoint, strict=True)
  File "/usr/local/lib/python3.5/dist-packages/mmcv-0.2.12-py3.5-linux-x86_64.egg/mmcv/runner/checkpoint.py", line 171, in load_checkpoint
    raise IOError('{} is not a checkpoint file'.format(filename))
OSError: tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth is not a checkpoint file

I am using"
pytorch 1.0
torchvision 0.2
python3.5

Do you know what going on??

**Comment by jiangzhubo** [comment]
solved

**Comment by cinjon** [comment]
what was the solution @jiangzhubo

**Comment by maxshng** [comment]
same problem found. 

"OSError: tsn_2d_rgb_bninception_seg3_f1s1_b32_g8-98160339.pth is not a checkpoint file" 
What to do?

**Comment by QAQ33** [comment]
same problem，how to solve it ,please tell me ,thank u @jiangzhubo

**Comment by QAQ33** [comment]
> same problem，how to solve it ,please tell me ,thank u @jiangzhubo

maybe the file path is not specified

**Comment by nfyjm** [comment]
same problem, how to resolve? @jiangzhubo

**Comment by nfyjm** [comment]
Got it! see source code 'mmcv/runner/checkpoint.py", load_checkpoint
(my mmcv version is 0.4.3) must exists prefix such as: 
    if filename.startswith('modelzoo://'):
        warnings.warn('The URL scheme of "modelzoo://" is deprecated, please '
                      'use "torchvision://" instead')
        model_urls = get_torchvision_models()
        model_name = filename[11:]
        checkpoint = load_url_dist(model_urls[model_name])
    elif filename.startswith('torchvision://'):
        model_urls = get_torchvision_models()
        model_name = filename[14:]
        checkpoint = load_url_dist(model_urls[model_name])
    elif filename.startswith('open-mmlab://'):
        model_name = filename[13:]
        checkpoint = load_url_dist(open_mmlab_model_urls[model_name])
    elif filename.startswith(('http://', 'https://')):
        checkpoint = load_url_dist(filename)
    else:
        if not osp.isfile(filename):
            raise IOError('{} is not a checkpoint file'.format(filename))
        checkpoint = torch.load(filename, map_location=map_location)

**Comment by nfyjm** [comment]
but now  it still occurs some errors like:  @jiangzhubo
...
KeyError: './modelzoo/tsn_2d_rgb_bninception_seg3_fis1_b32_g8-98160339.pth'
...
subprocess.CalledProcessError: Command '['/home/user/anaconda3/bin/python', '-u', './tools/test_recognizer.py', '--local_rank=0', 'test_configs/TSN/ucf101/tsn_rgb_bninception.py', 'open-mmlab://./modelzoo/tsn_2d_rgb_bninception_seg3_fis1_b32_g8-98160339.pth', '--launcher', 'pytorch']' returned non-zero exit status 1.
