### ISSUE TITLE
The model and loaded state dict do not match exactly

### ISSUE THREAD

**Issue by jiangzhubo** [open-mmlab/mmaction#78]
Hi, In traininig, when i run :
model = build_recognizer(  cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)

it turn out:
unexpected key in source state_dict: fc.weight, fc.bias

but seem the training can be started
i am using pytorch 1.0 
cuda 9.0
python3.5

can you tell me what this problem?

**Comment by innerlee** [comment]
The warning is harmless AFAIK
