### ISSUE TITLE
How to combine RGB and optical flow?

### ISSUE THREAD

**Issue by xzc1109** [open-mmlab/mmaction#80]
Hello! mmaction is an awesome code base, but i still have a question, in the paper [TSN](http://yjxiong.me/papers/eccv16tsn.pdf), refer to Table 2, when the input modality is combination of Optical Flow + Warped Flow + RGB the performance is best. How can I combine three different input together, since in mmaction there are only tsn_rgb and tsn_flow independently. I also noticed that in a caffee based [tsn](https://github.com/yjxiong/temporal-segment-networks) it can combine rbg and flow using 
`python tools/eval_scores.py output/rgb_score_file.npz output/flow_score_file.npz --score_weights 1 1.5`,
but in [test_rcognizer.py](https://github.com/open-mmlab/mmaction/blob/master/tools/test_recognizer.py) i didn't find any similar operation. I think the combination is just an aggregation process of scores which generated by  independently trained rgb and flow model, right? I'm looking forward for your answer!

**Comment by sparsh-b** [comment]
This paper might help:
Convolutional Two-Stream Network Fusion for Video Action Recognition

This is a medium blog post summarizing the paper:
https://medium.com/@g789872001darren/action-recognition-note-convolutional-two-stream-network-fusion-for-video-action-recognition-3de1690b5422

**Comment by yjxiong** [comment]
Simply adding scores together will be good enough for combining modalities. We will port the caffe tsn's eval_score utilities to test_recognizer. Thanks for the suggestion.

**Comment by xzc1109** [comment]
Thank you for your all replies, they are really helpful : ) !
