### ISSUE TITLE
could you provide a docker image ?

### ISSUE THREAD

**Issue by thxkew** [open-mmlab/mmaction#81]
I tried to build an enviralment  for MMACTION but got many error.
could you provide a docker image for easier way to set the enviralment ?

**Comment by mynameismaxz** [comment]
Yeah. I try to do the steps for docker environment. I'll try to pull request as soon as possible.

**Comment by mynameismaxz** [comment]
@thxkew Please checkout this : https://github.com/mynameismaxz/mmaction

**Comment by cow8** [comment]
may this branch merge into master? @mynameismaxz

**Comment by mynameismaxz** [comment]
> may this branch merge into master? @mynameismaxz
Yes, as soon as possible.
