### ISSUE TITLE
I3D model trained on Kinetics TV-L1

### ISSUE THREAD

**Issue by lixzhang** [open-mmlab/mmaction#84]
Thanks for sharing your great work. Do you have plans to publish the I3D model trained on Kinetics TV-L1? I saw the link to the model trained on Kinetics RGB but not Kinetics TV-L1.

**Comment by innerlee** [comment]
It is said that there were little improvement with flow in this case. (Personal advice is, do not expect too much on that.)

**Comment by yjxiong** [comment]
This is in the plan but not proritized yet. Two-stream I3Ds do introduce some non-trivial improvement in accuracy and we encourage you to try out training it.

**Comment by kennymckormick** [comment]
We have released the I3D-TVL1 model for Kinetics 400 now.
