### ISSUE TITLE
How to get the softmax scores for each frame using TSN?

### ISSUE THREAD

**Issue by Noone65536** [open-mmlab/mmaction#93]
Hello. I'd like to  use the softmax scores for each frame in TSN for further research. But the output file only contains the average scores of all the frames.  Where should I modify to get the frame scores when testing videos? Thank you very much.

**Comment by kennymckormick** [comment]
You can build a dataset for all frames in the videos. Then forward each frame the backbone + avg_pooling + cls_head.
