### ISSUE TITLE
How to run multi train scripts?

### ISSUE THREAD

**Issue by xiadingZ** [open-mmlab/mmaction#94]
I want to run multi train simultaneously, but it says
`RuntimeError: Address already in use`
How to change the config file to solve this problem?

**Comment by zhaoyue-zephyrus** [comment]
Hi @xiadingZ 

You can add an additional param `--master_port=XXXX` in `tools/dist_train_detector.sh`.

Reference: https://github.com/pytorch/pytorch/blob/master/torch/distributed/launch.py#L39
