### ISSUE TITLE
mean AP is 'nan'

### ISSUE THREAD

**Issue by thxkew** [open-mmlab/mmaction#95]
I tried to run test_localizer with thumos14_tag_test_proposal_list.txt contain just 2 videos 

when I run localizer evaluation as

python tools/test_localizer.py configs/thumos14/ssn_thumos14_rgb_bn_inception.py modelzoo/ssn_thumos14_rgb_bn_inception_tag-dac9ddb0.pth --gpus 8 --out ssn_thumos14_rgb_bn_inception.pkl --eval thumos14

I got the error below

#####################################################################
1 out of 2 videos are valid.

            SSNDataset: proposal file data/thumos14/thumos14_tag_test_proposal_list.txt parsed.

[                                                  ] 0/1, elapsed: 0s, ETA:The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

The model and loaded state dict do not match exactly

unexpected key in source state_dict: fc.weight, fc.bias

[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 1/1, 0.1 task/s, elapsed: 7s, ETA:     0s

writing results to ssn_thumos14_rgb_bn_inception.pkl
Starting evaluate thumos14
Performing location regression
Regression finished
Performing NMS
NMS finished

/root/mmaction/mmaction/third_party/ActivityNet/Evaluation/eval_detection.py:253: RuntimeWarning: invalid value encountered in true_divide
  recall_cumsum = tp_cumsum / npos
/root/mmaction/mmaction/third_party/ActivityNet/Evaluation/eval_detection.py:253: RuntimeWarning: invalid value encountered in true_divide
  recall_cumsum = tp_cumsum / npos
.
.
.
/root/mmaction/mmaction/third_party/ActivityNet/Evaluation/eval_detection.py:253: RuntimeWarning: invalid value encountered in true_divide
  recall_cumsum = tp_cumsum / npos
/root/mmaction/mmaction/third_party/ActivityNet/Evaluation/eval_detection.py:253: RuntimeWarning: invalid value encountered in true_divide
  recall_cumsum = tp_cumsum / npos
Evaluation finished
+Temporal detection performance (thumos14)------+------+------+------+------+
| IoU thresh | 0.10 | 0.20 | 0.30 | 0.40 | 0.50 | 0.60 | 0.70 | 0.80 | 0.90 |
+------------+------+------+------+------+------+------+------+------+------+
| mean AP    | nan  | nan  | nan  | nan  | nan  | nan  | nan  | nan  | nan  |
+------------+------+------+------+------+------+------+------+------+------+

########################################################################
mean AP is 'nan' it's a strange result. 
how to solve it ?

**Comment by zyzray** [comment]
If there is no ground truth in the videos, you will get this error. Check your test dataset.
