### ISSUE TITLE
Provide a simple demo script for recognizing actions on any video

### ISSUE THREAD

**Issue by bryanyzhu** [open-mmlab/mmaction#96]
Hi, thank you for the great work. Right now, I want to use your trained model to test on my own data to recognize human actions. However. I find it a little bit hard to do that. This code base is very modular, which is good for maintaining but hard to modify. 

For example, if I load a video and I have a torch tensor `video_data` of `1x3x64x224x224`, and I build a network like this 
```
cfg = mmcv.Config.fromfile('./i3d_kinetics400_3d_rgb_r50_c3d_inflate3x1x1_seg1_f32s2.py')
model = build_recognizer(cfg.model, train_cfg=None, test_cfg=cfg.test_cfg)
```
I want to do a simple inference like below
```
output = model(video_data)
```
There will be this error, `forward() missing 1 required positional argument: 'img_meta'`. Do I have to provide `img_meta` and use `DC from mmcv` to wrap the data to do the inference? Can you provide a simple demo script without too much dependency on mmcv? Thank you very much.

**Comment by yjxiong** [comment]
Hi, I think img_meta is not currently not used in the TSN3D recognizer, which means you can pass a `None` to make it work. 

@zhaoyue-zephyrus Please add documentations to the base classes for the models in mmaction.

**Comment by bryanyzhu** [comment]
@yjxiong Thank you for your quick reply, it works.

**Comment by qintao361** [comment]
@yjxiong is it possible to provide a inference demo about ssn model? thanks a lot.

**Comment by Mang0o** [comment]
hi, Yi Zhu, thank you for the great work. @yjxiong Could you please provide the whole demo script for recognizing actions on single video? Thanks you very much!
