### ISSUE TITLE
CMAKE cannot find ffmpeg

### ISSUE THREAD

**Issue by ghost** [open-mmlab/mmaction#98]
Hello,

I am trying to compile decord with ffmpeg 4 installed as suggested in INSTALL.md. I am facing  error,

```bash
-- Checking for module 'libavformat'
--   No package 'libavformat' found
-- Checking for module 'libavfilter'
--   No package 'libavfilter' found
CMake Error at cmake/modules/FFmpeg.cmake:27 (message):
  Unable to find FFMPEG automatically, please specify FFMPEG location
Call Stack (most recent call first):
  CMakeLists.txt:91 (include)
```
The system is ubuntu 18.04. Could you please help me fix this

**Comment by mynameismaxz** [comment]
@venkatesh369 
I think you should install an additional package from this list
-     libavcodec-dev
-     libavfilter-dev
-     libavformat-dev
-     libavutil-dev

**Comment by kennymckormick** [comment]
You can install decord via 'pip install decord' now, which is much easier.
