### ISSUE TITLE
How to finetune I3D pretrained on Kinetics on UCF101？

### ISSUE THREAD

**Issue by chenyihang1993** [open-mmlab/mmaction#99]
How to finetune I3D pretrained on Kinetics on UCF101? Is there any code about this?

**Comment by zhaoyue-zephyrus** [comment]
Hi @chenyihang1993 

The example for fine-tuning on UCF-101 has been made available in the latest PR (https://github.com/open-mmlab/mmaction/pull/142).

**Comment by cinjon** [comment]
Hi @zhaoyue-zephyrus , I don't see an example for fine-tuning in that PR. Do you mind pointing a link to where this is?

**Comment by liu666666** [comment]
@cinjon @zhaoyue-zephyrus 
I don't see an example for fine-tuning in that PR, either. Is this problem solved?
